import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
const {chromium}=await import(process.env.PNEUMA_PLAYWRIGHT_MODULE);
const browser=await chromium.launch({channel:"msedge",headless:true});
try{
 const page=await browser.newPage({viewport:{width:1100,height:800}});
 await page.emulateMedia({reducedMotion:"no-preference"});
 await page.setContent('<style>body{background:#17222c}</style><aside id="sidebar" style="position:fixed;right:0;top:0;width:300px;height:100vh"></aside><div id="chat-log"><div data-message-id="attack">Chat resolution</div></div>');
 await page.addStyleTag({content:await readFile("dist/styles/pneuma-combattools.css","utf8")});
 await page.evaluate(()=>{
  window.FormApplication=class {};
  window.Dialog=class {constructor(data){window.messageDialog=data;}render(){return this;}};
  window.hooks={};window.Hooks={on:(k,f)=>(hooks[k]??=[]).push(f),once:(k,f)=>(hooks[k]??=[]).push(f)};
  window.values={};window.settings={};
  window.actor={uuid:"Actor.test",name:"Smitty",isOwner:true,system:{derivedStats:{hp:{value:40,max:40}}},items:[{type:"criticalInjury",name:"Crushed Windpipe"}],
    allApplicableEffects:()=>[{name:"Crushed Windpipe",statuses:new Set(["windpipe"])},{name:"Prone",statuses:new Set(["prone"])},{name:"Disabled",disabled:true,statuses:new Set(["disabled"])}],
    sheet:{render:()=>{window.openedSheet=true;}}};
  window.moduleEntry={api:{existing:true}};window.socketListeners=[];window.sentPackets=[];
  window.game={modules:{get:()=>moduleEntry},socket:{on:(_channel,fn)=>socketListeners.push(fn),emit:(_channel,wire)=>sentPackets.push(wire)},user:{id:"player",isGM:false,character:actor},users:{[Symbol.iterator]:function*(){yield {id:"player",name:"Player",active:true,isGM:false};},filter:fn=>[{id:"player",active:true,isGM:false}].filter(fn),get:id=>id==="player"?{id,active:true}:undefined},i18n:{localize:s=>s},messages:[],settings:{
    registerMenu:()=>{},register:(_m,k,c)=>{settings[k]=c;values[k]=c.default;},get:(_m,k)=>values[k],
    set:async(_m,k,v)=>{values[k]=v;settings[k].onChange?.(v);}
  }};
  window.canvas={tokens:{controlled:[]}};
  window.foundry={utils:{randomID:()=>String(window.testMessageId=(window.testMessageId??0)+1),getProperty:(o,p)=>p.split(".").reduce((v,k)=>v?.[k],o)}};
  window.ui={sidebar:{activateTab:()=>{window.openedChat=true;}},notifications:{info:()=>{}}};
 });
 await page.addScriptTag({type:"module",content:(await readFile("dist/scripts/socket-health.js","utf8")).replace('const MODULE = "pneuma-combattools";','const SOCKET_MODULE = "pneuma-combattools";').replace("get(MODULE)","get(SOCKET_MODULE)")+"\n"+(await readFile("dist/scripts/hud-messages.js","utf8")).replace(/^import .*;\s*/gm,"")+"\n"+(await readFile("dist/scripts/item-markers.js","utf8")).replace('const MODULE = "pneuma-combattools";', "")+"\n"+(await readFile("dist/scripts/biomonitor.js","utf8"))+"\n"+(await readFile("dist/scripts/grapple/rules.js","utf8"))+"\n"+(await readFile("dist/scripts/grapple/state.js","utf8")).replace(/^import .*;\s*/gm,"").replace('export const MODULE = "pneuma-combattools";', "")+"\nconst movementHUD=()=>[]; const grappleProperty = property;\n"+(await readFile("dist/scripts/status-catalog.js","utf8"))+"\n"+(await readFile("dist/scripts/hud-conditions.js","utf8")).replace(/^import .*;\s*/gm,"")+"\n"+(await readFile("dist/scripts/eye-hud.js","utf8")).replace(/^import .*;\s*/gm,"")+"\nObject.assign(window,{sendHUDMessage,hasBiomonitor,collectHUDConditions});registerEyeHUD();"});
 await page.waitForFunction(()=>hooks.ready?.length);
 await page.evaluate(()=>{hooks.ready.forEach(f=>f());});
 await page.waitForSelector('.pneuma-eye-medical');
 assert.equal(await page.evaluate(()=>settings.eyeHUDAnimateMessages.scope),'client');
 assert.equal(await page.evaluate(()=>values.eyeHUDAnimateMessages),true);
 await page.evaluate(()=>moduleEntry.api.hud.send({source:'animation',id:'arrival',text:'New transmission'}));
 await page.waitForSelector('.pneuma-eye-notification');
 const arrival=await page.evaluate(()=>{
  const text=document.querySelector('.pneuma-eye-notification').firstElementChild;
  window.arrivalText=text; window.arrivalAnimation=text.getAnimations()[0];
  arrivalAnimation.pause();arrivalAnimation.currentTime=400;
  const b=text.getBoundingClientRect();
  return {x:b.x+b.width/2,y:b.y+b.height/2,w:b.width,screenX:innerWidth/2,screenY:innerHeight/2,color:getComputedStyle(text).color};
 });
 assert.ok(Math.abs(arrival.x-arrival.screenX)<2 && Math.abs(arrival.y-arrival.screenY)<2,'Arrival starts at screen center');
 assert.equal(arrival.color,'rgb(255, 180, 95)');
 const scan=await page.evaluate(()=>{
  arrivalAnimation.currentTime=100;const reveal=getComputedStyle(arrivalText).clipPath;
  arrivalAnimation.currentTime=800;const hold=getComputedStyle(arrivalText).clipPath;
  arrivalAnimation.currentTime=1290;const collapsed=getComputedStyle(arrivalText).clipPath;
  const center=arrivalText.getBoundingClientRect();
  arrivalAnimation.currentTime=1380;const blackout=getComputedStyle(arrivalText).opacity;
  arrivalAnimation.currentTime=400;
  return {reveal,hold,collapsed,blackout,centerX:center.x+center.width/2,line:!!arrivalText.querySelector('.pneuma-eye-scanline')};
 });
 assert.notEqual(scan.reveal,scan.hold,'Scan progressively reveals text');
 assert.equal(scan.collapsed,'inset(49% 0px)','Center message collapses to a narrow horizontal line');
 assert.equal(scan.blackout,'0','Relocation occurs while invisible');
 assert.ok(Math.abs(scan.centerX-arrival.screenX)<2,'Message stays centered through collapse instead of flying');
 assert.equal(scan.line,true,'Visible scan beam is present');

 await page.evaluate(()=>moduleEntry.api.hud.send({source:'animation',id:'second',text:'Second transmission'}));
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-notification').length===2);
 assert.equal(await page.evaluate(()=>arrivalText===document.querySelector('.pneuma-eye-notification').firstElementChild && arrivalText.getAnimations()[0]===arrivalAnimation),true,'Existing arrivals survive notification refresh without replay');
 const landed=await page.evaluate(()=>{arrivalAnimation.finish();const b=arrivalText.getBoundingClientRect();const hud=document.getElementById('pneuma-eye-hud').getBoundingClientRect();return {w:b.width,y:b.y,bottom:hud.bottom};});
 assert.ok(arrival.w>landed.w*2,'Docked text returns to normal size');
 assert.ok(landed.y>=landed.bottom,'Message lands below HUD');
 await page.waitForFunction(()=>!arrivalText.querySelector('.pneuma-eye-scanline'));
 await page.evaluate(()=>game.settings.set('pneuma-combattools','eyeHUDAnimateMessages',false));
 assert.equal(await page.evaluate(()=>Array.from(document.querySelectorAll('.pneuma-eye-notification > :first-child')).some(t=>t.getAnimations().length)),false,'Disabling cancels active arrivals');
 await page.evaluate(()=>{moduleEntry.api.hud.list().forEach(n=>moduleEntry.api.hud.dismiss(n.source,n.id));moduleEntry.api.hud.send({source:'animation',id:'disabled',text:'Direct notice'});});
 await page.waitForFunction(()=>document.querySelector('.pneuma-eye-notification')?.textContent.includes('Direct notice'));
 assert.equal(await page.locator('.pneuma-eye-notification > :first-child').evaluate(t=>t.getAnimations().length),0);
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.evaluate(()=>{game.settings.set('pneuma-combattools','eyeHUDAnimateMessages',true);moduleEntry.api.hud.list().forEach(n=>moduleEntry.api.hud.dismiss(n.source,n.id));moduleEntry.api.hud.send({source:'animation',id:'reduced',text:'Reduced motion'});});
 await page.waitForFunction(()=>document.querySelector('.pneuma-eye-notification')?.textContent.includes('Reduced motion'));
 assert.equal(await page.locator('.pneuma-eye-notification > :first-child').evaluate(t=>t.getAnimations().length),0);
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.evaluate(()=>moduleEntry.api.hud.list().forEach(n=>moduleEntry.api.hud.dismiss(n.source,n.id)));
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-notification'));

 assert.equal(await page.locator('.pneuma-eye-conditions .pneuma-eye-condition').count(),1,'Prone must not appear as pathology');
 assert.equal(await page.locator('.pneuma-eye-situation').innerText(),'PRONE');
 assert.equal(await page.locator('.pneuma-eye-effect-arrival').count(),0,'Existing conditions establish baseline without announcements');
 await page.evaluate(()=>{
  window.beforeActivation=actor.allApplicableEffects;values.biomonitorFlashSeconds=0;
  actor.allApplicableEffects=()=>[...beforeActivation(),{name:'Boost Primary',statuses:new Set()},{name:'Poison',statuses:new Set(['poison'])}];
  hooks.updateActor.forEach(f=>f(actor));
 });
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-effect-arrival').length===2);
 assert.equal(await page.locator('#pneuma-eye-hud .is-arriving').count(),2,'Dashboard waits for announcement');
 const blink=await page.evaluate(()=>{
  const node=document.querySelector('.pneuma-eye-effect-arrival');
  window.effectAnimation=node.getAnimations()[0];effectAnimation.pause();
  return [850,1000,1180,1330,1520,1700].map(time=>{effectAnimation.currentTime=time;return getComputedStyle(node).opacity;});
 });
 assert.deepEqual(blink,['0','1','0','1','0','1'],'Three distinct off/on blinks');
 await page.evaluate(()=>hooks.updateActor.forEach(f=>f(actor)));
 await page.waitForTimeout(40);
 assert.equal(await page.evaluate(()=>document.querySelector('.pneuma-eye-effect-arrival').getAnimations()[0]===effectAnimation),true,'Refresh preserves current activation');
 await page.evaluate(()=>document.querySelectorAll('.pneuma-eye-effect-arrival').forEach(node=>node.getAnimations().forEach(a=>a.finish())));
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-effect-arrival'));
 assert.equal(await page.locator('#pneuma-eye-hud .is-arriving').count(),0,'Dashboard lights after sequence');
 await page.evaluate(()=>{actor.allApplicableEffects=beforeActivation;hooks.updateActor.forEach(f=>f(actor));});
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-drug-light'));
 await page.evaluate(()=>{actor.allApplicableEffects=()=>[...beforeActivation(),{name:'Boost Primary',statuses:new Set()}];hooks.updateActor.forEach(f=>f(actor));});
 await page.waitForSelector('.pneuma-eye-effect-arrival');
 await page.evaluate(()=>game.settings.set('pneuma-combattools','eyeHUDAnimateMessages',false));
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-effect-arrival'));
 assert.equal(await page.locator('#pneuma-eye-hud .is-arriving').count(),0,'Disable immediately releases dashboard');
 await page.evaluate(()=>{actor.allApplicableEffects=beforeActivation;hooks.updateActor.forEach(f=>f(actor));});
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-drug-light'));
 await page.evaluate(()=>game.settings.set('pneuma-combattools','eyeHUDAnimateMessages',true));

 assert.equal(await page.locator('#pneuma-eye-hud .pneuma-eye-alert').count(),0);
 assert.equal(await page.locator('.pneuma-eye-drug-light').count(),0);
 assert.equal(await page.locator('.pneuma-eye-drug-lights').isVisible(),false);
 assert.equal(await page.locator('.pneuma-eye-ekg + .pneuma-eye-vital-state').count(),1,'Wound label must immediately follow EKG');
 await page.evaluate(()=>{
  window.savedEffects=actor.allApplicableEffects;
  actor.allApplicableEffects=()=>['Black Lace Primary','Blue Glass','Boost Primary','Smash Primary','Synthcoke Addicted Primary','Berserker','Prime Time','Sixgun Addiction Primary','Timewarp Primary','Antibiotic','Stim','Surge','Quick Fix','Sedative','Veritas Primary'].map(name=>({name,statuses:new Set()}));
  hooks.updateActor.forEach(f=>f(actor));
 });
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-drug-light').length===15);
 assert.equal(await page.locator('.pneuma-eye-drug-light[data-kind=drug]').count(),9);
 assert.equal(await page.locator('.pneuma-eye-drug-light[data-kind=pharma]').count(),6);
 await page.evaluate(()=>{
  actor.allApplicableEffects=()=>[{name:'Veritas Primary',statuses:new Set()},{name:'Timewarp Addiction',statuses:new Set()},{name:'Berserker Addiction',statuses:new Set()},{name:'Sedative',disabled:true,statuses:new Set(['sedative'])}];
  hooks.updateActor.forEach(f=>f(actor));
 });
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-drug-light').length===1);
 assert.match(await page.locator('.pneuma-eye-drug-light').getAttribute('aria-label'),/Veritas/);
 const rowLeft=await page.locator('.pneuma-eye-drug-lights').boundingBox();
 const iconLeft=await page.locator('.pneuma-eye-drug-light').boundingBox();
 assert.equal(iconLeft.x,rowLeft.x,'Only Veritas still occupies the leftmost slot');
 assert.equal(await page.locator('.pneuma-eye-lamp[data-kind=addict]').count(),1,'Native supplemental addiction activates only the summary lamp');
 await page.evaluate(()=>{actor.allApplicableEffects=savedEffects;hooks.updateActor.forEach(f=>f(actor));});
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-drug-light'));
 assert.equal(await page.locator('.pneuma-eye-drug-lights').isVisible(),false);
 assert.equal(await page.locator('.pneuma-eye-notification').count(),0);
 assert.equal(await page.locator('#pneuma-eye-hud > .pneuma-eye-header').count(),0);
 assert.equal(await page.locator('.pneuma-eye-cyber-heading [aria-label="Minimize status HUD"]').count(),1);
 assert.equal(await page.locator('.pneuma-eye-identity').count(),0);
 await page.evaluate(()=>{
  window.effects=[{name:'Boost Primary',statuses:new Set()},{name:'Stim',statuses:new Set()},{name:'Synthcoke Addiction',statuses:new Set(['addiction'])},{name:'Sleep — Unconscious',statuses:new Set(['unconscious'])},{name:'Cover',statuses:new Set(['cover'])},{name:'Speed Heal',statuses:new Set(['speedheal'])},{name:'Netrunning',statuses:new Set(['netrunning'])}];
  actor.allApplicableEffects=()=>effects;
  hooks.updateActor.forEach(f=>f(actor));
 });
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-drug-light.is-on').length===2);
 assert.equal(await page.locator('.pneuma-eye-lamp[data-kind=addict].is-on').count(),1);
 assert.equal(await page.locator('.pneuma-eye-lamp[data-kind=unconscious].is-on').count(),1);
 assert.equal(await page.locator('.pneuma-eye-lamp[data-kind=jacked].is-on').count(),0,'Netrunning marker is not an active Jack-In');
 assert.doesNotMatch(await page.locator('.pneuma-eye-conditions').innerText(),/Boost|Stim|Speed|Addiction|Cover/);
 await page.evaluate(()=>{game.combat={started:true,flags:{'pneuma-combattools':{quickhackConnections:{a:{sourceActorUuid:actor.uuid,state:'active'}}}}};hooks.updateCombat.forEach(f=>f());});
 await page.waitForSelector('.pneuma-eye-lamp[data-kind=jacked].is-on');
 await page.evaluate(()=>{effects[0].disabled=true;effects[1].isSuppressed=true;hooks.updateActor.forEach(f=>f(actor));});
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-drug-light.is-on'));
 await page.evaluate(()=>{
  window.stableEKG=document.querySelector('.pneuma-eye-ekg');
  window.message={id:'attack',visible:true,isContentVisible:true,flags:{'pneuma-combattools':{exchange:{state:'waiting',defenderActor:actor.uuid,total:99,title:'SECRET'}}}};
  hooks.createChatMessage.forEach(f=>f(message));
 });
 await page.waitForSelector('.pneuma-eye-notification.is-attack');
 assert.equal(await page.evaluate(()=>stableEKG===document.querySelector('.pneuma-eye-ekg')),true,'Messages must not rebuild vitals');
 assert.equal(await page.locator('#pneuma-eye-hud .pneuma-eye-notification').count(),0);
 assert.doesNotMatch(await page.locator('#pneuma-eye-attachments').innerText(),/99|SECRET/);
 await page.getByRole('button',{name:'Incoming attack: open chat card',exact:true}).click();
 assert.equal(await page.evaluate(()=>openedChat),true);
 await page.evaluate(()=>{
  window.other={uuid:'Actor.other',name:'Vex',isOwner:false,system:{derivedStats:{hp:{value:12,max:40}}},items:[{type:'cyberware',name:'Biomonitor',system:{isInstalledInActor:true}}],allApplicableEffects:()=>[{name:'Hidden',statuses:new Set(['hidden'])}]};
  window.token={actor:other,isVisible:true,isPreview:false};canvas.activeLayer=canvas.tokens;
  hooks.hoverToken.forEach(f=>f(token,true));
 });
 await page.waitForFunction(()=>document.querySelector('.pneuma-eye-identity')?.textContent.includes('Vex · BIOMONITOR LINK'));
 assert.equal(await page.locator('.pneuma-eye-hp strong').innerText(),'12');
 assert.equal(await page.locator('.pneuma-eye-notification-owner').count(),0);
 assert.match(await page.locator('.pneuma-eye-notifications').getAttribute('aria-label'),/Smitty/);
 assert.equal(await page.locator('.pneuma-eye-notification').first().evaluate(n=>getComputedStyle(n).fontSize),'24px');
 assert.equal(await page.locator('.pneuma-eye-notification').first().evaluate(n=>getComputedStyle(n).color),'rgb(255, 180, 95)');
 assert.equal(await page.locator('.pneuma-eye-notification.is-attack').count(),1,'Own attack remains while viewing someone else');
 await page.evaluate(()=>hooks.hoverToken.forEach(f=>f(token,false)));
 await page.waitForFunction(()=>document.querySelector('#pneuma-eye-hud')?.getAttribute('aria-label').includes('Smitty'));
 await page.evaluate(()=>{other.items=[];hooks.hoverToken.forEach(f=>f(token,true));});
 await page.waitForTimeout(40);
 assert.match(await page.locator('#pneuma-eye-hud').getAttribute('aria-label'),/Smitty/,'No implant means no shared HUD');
 await page.evaluate(()=>{for(let i=0;i<5;i++)moduleEntry.api.hud.send({source:'test',id:String(i),text:'Notice '+i,duration:0});});
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-notification').length===3);
 assert.equal(await page.evaluate(()=>moduleEntry.api.hud.list().length),3);
 assert.equal(await page.evaluate(()=>moduleEntry.api.hud.list().every(n=>n.expires>Date.now())),true,'Ordinary messages expire even with legacy duration=0');
 await page.getByRole('button',{name:'Clear notification: Incoming Attack',exact:true}).click();
 assert.equal(await page.evaluate(()=>message.flags['pneuma-combattools'].exchange.state),'waiting','Dismiss does not resolve an attack');
 await page.evaluate(()=>{moduleEntry.api.hud.list().forEach(n=>moduleEntry.api.hud.dismiss(n.source,n.id));moduleEntry.api.hud.send({source:'test',id:'expiry',text:'Short notice',duration:.05});});
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-notification'));
 await page.evaluate(()=>{window.originalEffects=effects;effects=effects.filter(e=>e.name!=='Cover');hooks.updateActor.forEach(f=>f(actor));});
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-situation').length===0);
 const withoutStatus=await page.locator('#pneuma-eye-hud').boundingBox();
 await page.evaluate(()=>{effects=originalEffects;hooks.updateActor.forEach(f=>f(actor));});
 await page.evaluate(()=>{effects.push({name:'Prone',statuses:new Set(['prone'])});hooks.updateActor.forEach(f=>f(actor));});
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-situation').length===2);
 assert.equal(await page.locator('#pneuma-eye-hud .pneuma-eye-situation').count(),2,'Statuses must be inside the HUD');
 const bounds=await page.locator('#pneuma-eye-hud').boundingBox();
 assert.equal(bounds.height,withoutStatus.height,'Floating statuses must not increase HUD height');
 assert.equal(bounds.width,withoutStatus.width,'Floating statuses must not increase HUD width');
 const dockBounds=await page.locator('.pneuma-eye-status-dock').boundingBox();
 assert.ok(dockBounds.y+dockBounds.height<=bounds.y+bounds.height,'Dock stays inside lower edge');
 const positions=await page.locator('.pneuma-eye-situation').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().x));
 assert.ok(positions[0]>positions[1],'Subsequent statuses extend left');
 await page.getByRole('button',{name:'Minimize status HUD',exact:true}).click();
 await page.waitForSelector('#pneuma-eye-hud.is-minimized');
 assert.equal(await page.locator('.pneuma-eye-status-dock').isVisible(),false);
 await page.getByRole('button',{name:'Expand status HUD',exact:true}).click();
 await page.waitForSelector('.pneuma-eye-medical');
 assert.equal(await page.getByRole('button',{name:'Minimize status HUD',exact:true}).count(),1,'Expand must not duplicate inline controls');
 const initial=await page.locator('#pneuma-eye-hud').boundingBox();
 await page.locator('.pneuma-eye-conditions .pneuma-eye-medical-label').hover();await page.mouse.down();await page.mouse.move(initial.x-40,initial.y+50);await page.mouse.up();
 assert.equal(await page.evaluate(()=>values.eyeHUDPosition),null,'Docking leaves saved drag position untouched');
 assert.deepEqual(await page.locator('#pneuma-eye-hud').boundingBox(),initial,'Dragging is inactive');
 async function assertDocked(){
  await page.waitForFunction(()=>{const h=document.getElementById('pneuma-eye-hud').getBoundingClientRect();const d=document.getElementById('sidebar').getBoundingClientRect();return Math.abs(h.right-(d.left-8))<1 && h.top===8;});
  const b=await page.locator('#pneuma-eye-hud').boundingBox();
  assert.ok(b.x>=7,'HUD fits available viewport');
  assert.ok(await page.locator('#pneuma-eye-attachments').evaluate(e=>e.getBoundingClientRect().right<=document.getElementById('sidebar').getBoundingClientRect().left-7),'Notifications stay outside dock');
 }
 await assertDocked();
 await page.evaluate(()=>document.getElementById('sidebar').style.width='32px');
 await assertDocked();
 await page.evaluate(()=>document.getElementById('sidebar').style.width='300px');
 await assertDocked();
 await page.setViewportSize({width:800,height:800});
 await assertDocked();
 await page.setViewportSize({width:1100,height:800});
 await assertDocked();
 await page.evaluate(()=>{const old=document.getElementById('sidebar');const next=old.cloneNode();next.style.width='260px';old.replaceWith(next);hooks.renderSidebar.forEach(f=>f());});
 await assertDocked();
 await page.evaluate(()=>{game.user.isGM=true;canvas.tokens.controlled=[{actor,name:'Smitty'}];hooks.controlToken.forEach(f=>f());});
 await page.waitForSelector('.pneuma-eye-identity');
 assert.equal(await page.locator('.pneuma-eye-identity').innerText(),'Smitty');
 const gmHUD=await page.locator('#pneuma-eye-hud').boundingBox();
 const gmName=await page.locator('.pneuma-eye-identity').boundingBox();
 assert.ok(gmName.y>=gmHUD.y+gmHUD.height,'GM name below the HUD');
 assert.ok(Math.abs(gmName.x-gmHUD.x)<2,'GM name aligned to left edge');
 await page.getByRole('button',{name:'Minimize status HUD',exact:true}).click();
 await page.waitForSelector('#pneuma-eye-hud.is-minimized');
 await assertDocked();
 const miniHUD=await page.locator('#pneuma-eye-hud').boundingBox();
 const miniName=await page.locator('.pneuma-eye-identity').boundingBox();
 assert.ok(Math.abs(miniName.x-miniHUD.x)<2,'Name follows minimized HUD left edge');
 assert.ok(miniName.y>=miniHUD.y+miniHUD.height,'Name remains below minimized HUD');
 assert.ok(Math.abs(miniName.width-miniHUD.width)<2,'Name width follows minimized HUD');
 await page.getByRole('button',{name:'Expand status HUD',exact:true}).click();
 await page.waitForSelector('.pneuma-eye-medical');
 const expandedHUD=await page.locator('#pneuma-eye-hud').boundingBox();
 const expandedName=await page.locator('.pneuma-eye-identity').boundingBox();
 assert.ok(Math.abs(expandedName.x-expandedHUD.x)<2,'Name returns to expanded HUD left edge');
 assert.equal(await page.locator('#pneuma-eye-hud > .pneuma-eye-header').count(),0);
 await page.evaluate(()=>game.settings.set('pneuma-combattools','eyeHUDPreview',true));
 await page.waitForSelector('[aria-label="Test HP state"]');
 await page.getByLabel('Test HP state').selectOption('30');
 await page.waitForFunction(()=>document.querySelector('.pneuma-eye-vitals').dataset.state==='wounded');
 await page.screenshot({path:process.env.TEMP+'/pneuma-eye-hud-redesign.png'});
 await page.evaluate(()=>game.settings.set('pneuma-combattools','eyeHUDPreview',false));
 await page.evaluate(()=>game.settings.set('pneuma-combattools','eyeHUD',false));
 await page.waitForFunction(()=>!document.getElementById('pneuma-eye-hud')&&!document.getElementById('pneuma-eye-attachments'));
 console.log('HUD browser regression passed: classification, native drugs, sharing, private messages, expiry, docking, drag, preview.');
}finally{await browser.close();}
