import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
const {chromium}=await import(process.env.PNEUMA_PLAYWRIGHT_MODULE);
const browser=await chromium.launch({channel:"msedge",headless:true});
try{
 const page=await browser.newPage({viewport:{width:1100,height:800}});
 await page.emulateMedia({reducedMotion:"no-preference"});
 await page.setContent('<style>body{background:#17222c}</style><aside id="sidebar" style="position:fixed;right:0;top:0;width:300px;height:100vh"></aside><div id="chat-log"><div data-message-id="attack">Chat resolution</div></div>');
 await page.addStyleTag({content:(await readFile("dist/styles/pneuma-combattools.css","utf8")).replace("icons/biomon-alert.svg", "data:image/svg+xml;base64," + (await readFile("dist/styles/icons/biomon-alert.svg")).toString("base64"))});
 await page.evaluate(()=>{
  window.injuryGuidance={};window.FormApplication=class {};
  window.Dialog=class {constructor(data){window.messageDialog=data;}render(){return this;}};
  window.hooks={};window.Hooks={on:(k,f)=>(hooks[k]??=[]).push(f),once:(k,f)=>(hooks[k]??=[]).push(f)};
  window.values={};window.settings={};
  window.actor={uuid:"Actor.test",name:"Smitty",isOwner:true,system:{derivedStats:{hp:{value:40,max:40}}},items:[{type:"criticalInjury",name:"Crushed Windpipe"}],
    allApplicableEffects:()=>[{name:"Crushed Windpipe",statuses:new Set(["windpipe"])},{name:"Prone",statuses:new Set(["prone"])},{name:"Disabled",disabled:true,statuses:new Set(["disabled"])}],
    sheet:{render:()=>{window.openedSheet=true;}}};
  window.moduleEntry={api:{existing:true}};window.socketListeners=[];window.sentPackets=[];
  window.game={modules:{get:()=>moduleEntry},socket:{on:(_channel,fn)=>socketListeners.push(fn),emit:(_channel,wire)=>sentPackets.push(wire)},user:{id:"player",isGM:false,character:actor},users:{[Symbol.iterator]:function*(){yield {id:"player",name:"Player",active:true,isGM:false};},filter:fn=>[{id:"player",active:true,isGM:false}].filter(fn),get:id=>id==="player"?{id,active:true}:undefined},i18n:{localize:s=>s},messages:[],settings:{
    registerMenu:()=>{},register:(_m,k,c)=>{settings[k]=c;values[k]=c.default;},get:(_m,k)=>values[k],
    set:async(_m,k,v)=>{values[k]=v;settings[k].onChange?.(v);}
  }};
  window.canvas={tokens:{controlled:[]}};
  window.foundry={utils:{randomID:()=>String(window.testMessageId=(window.testMessageId??0)+1),getProperty:(o,p)=>p.split(".").reduce((v,k)=>v?.[k],o)}};
  window.ui={sidebar:{activateTab:()=>{window.openedChat=true;}},notifications:{info:()=>{}}};
 });
 await page.addScriptTag({type:"module",content:(await readFile("dist/scripts/socket-health.js","utf8")).replace('const MODULE = "pneuma-combattools";','const SOCKET_MODULE = "pneuma-combattools";').replace("get(MODULE)","get(SOCKET_MODULE)")+"\n"+(await readFile("dist/scripts/hud-messages.js","utf8")).replace(/^import .*;\s*/gm,"")+"\n"+(await readFile("dist/scripts/update-path.js","utf8"))+"\n"+(await readFile("dist/scripts/item-markers.js","utf8")).replace(/^import .*;\s*/gm,"").replace('const MODULE = "pneuma-combattools";', "")+"\n"+(await readFile("dist/scripts/biomonitor.js","utf8"))+"\n"+(await readFile("dist/scripts/grapple/rules.js","utf8"))+"\n"+(await readFile("dist/scripts/grapple/state.js","utf8")).replace(/^import .*;\s*/gm,"").replace('export const MODULE = "pneuma-combattools";', "")+"\nconst forceOutEntries=()=>window.testIncoming??[]; const bindStatusActions=()=>{}; const closeStatusActions=()=>{}; const createIntrusionGlitches=()=>({sync(){},stop(){}}); const movementHUD=()=>[]; const grappleProperty = property;\n"+(await readFile("dist/scripts/status-catalog.js","utf8"))+"\n"+(await readFile("dist/scripts/hud-conditions.js","utf8")).replace(/^import .*;\s*/gm,"")+"\n"+(await readFile("dist/scripts/eye-hud.js","utf8")).replace(/^import .*;\s*/gm,"")+"\nObject.assign(window,{sendHUDMessage,hasBiomonitor,collectHUDConditions});registerEyeHUD();"});
 const ts = (await import("../node_modules/typescript/lib/typescript.js")).default;
 const crewRoot = process.env.PNEUMA_CREWTOOLS_ROOT ?? "../PneumaCrewTools";
 const shortcutSource = await readFile(crewRoot + "/src/hud-shortcuts.ts", "utf8").catch(()=>null);
 if (shortcutSource) {
 await page.addStyleTag({content:await readFile(crewRoot + "/dist/styles/pneuma-crewtools.css","utf8")});
 await page.addScriptTag({type:"module",content:ts.transpile(shortcutSource,{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}) + "\nObject.assign(window,{hudShortcuts,refreshHudShortcuts});"});
 await page.waitForFunction(()=>window.hudShortcuts);
 await page.evaluate(()=>{
   window.crewEntry={active:true,api:{hudShortcuts}};
   game.modules.get=id=>id==='pneuma-crewtools'?crewEntry:moduleEntry;
 });
 }
 await page.waitForFunction(()=>hooks.ready?.length);
 await page.evaluate(()=>{hooks.ready.forEach(f=>f());});
 await page.waitForSelector('.pneuma-eye-medical');
 assert.equal(await page.evaluate(()=>settings.eyeHUDAnimateMessages.scope),'client');
 assert.equal(await page.evaluate(()=>values.eyeHUDAnimateMessages),true);
 await page.evaluate(()=>moduleEntry.api.hud.send({source:'animation',id:'arrival',text:'New transmission'}));
 await page.waitForSelector('.pneuma-eye-notification');
 const arrival=await page.evaluate(()=>{
  const text=document.querySelector('.pneuma-eye-notification').firstElementChild;
  window.arrivalText=text; window.arrivalAnimation=text.getAnimations()[0];
  arrivalAnimation.pause();arrivalAnimation.currentTime=400;
  const b=text.getBoundingClientRect();
  return {x:b.x+b.width/2,y:b.y+b.height/2,w:b.width,screenX:innerWidth/2,screenY:innerHeight/2,color:getComputedStyle(text).color};
 });
 assert.ok(Math.abs(arrival.x-arrival.screenX)<2 && Math.abs(arrival.y-arrival.screenY)<2,'Arrival starts at screen center');
 assert.equal(arrival.color,'rgb(255, 180, 95)');
 const scan=await page.evaluate(()=>{
  arrivalAnimation.currentTime=100;const reveal=getComputedStyle(arrivalText).clipPath;
  arrivalAnimation.currentTime=800;const hold=getComputedStyle(arrivalText).clipPath;
  arrivalAnimation.currentTime=1290;const collapsed=getComputedStyle(arrivalText).clipPath;
  const center=arrivalText.getBoundingClientRect();
  arrivalAnimation.currentTime=1380;const blackout=getComputedStyle(arrivalText).opacity;
  arrivalAnimation.currentTime=400;
  return {reveal,hold,collapsed,blackout,centerX:center.x+center.width/2,line:!!arrivalText.querySelector('.pneuma-eye-scanline')};
 });
 assert.notEqual(scan.reveal,scan.hold,'Scan progressively reveals text');
 assert.equal(scan.collapsed,'inset(49% 0px)','Center message collapses to a narrow horizontal line');
 assert.equal(scan.blackout,'0','Relocation occurs while invisible');
 assert.ok(Math.abs(scan.centerX-arrival.screenX)<2,'Message stays centered through collapse instead of flying');
 assert.equal(scan.line,true,'Visible scan beam is present');

 await page.evaluate(()=>moduleEntry.api.hud.send({source:'animation',id:'second',text:'Second transmission'}));
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-notification').length===2);
 assert.equal(await page.evaluate(()=>arrivalText===document.querySelector('.pneuma-eye-notification').firstElementChild && arrivalText.getAnimations()[0]===arrivalAnimation),true,'Existing arrivals survive notification refresh without replay');
 const landed=await page.evaluate(()=>{arrivalAnimation.finish();const b=arrivalText.getBoundingClientRect();const hud=document.getElementById('pneuma-eye-hud').getBoundingClientRect();return {w:b.width,y:b.y,bottom:hud.bottom};});
 assert.ok(arrival.w>landed.w*2,'Docked text returns to normal size');
 assert.ok(landed.y>=landed.bottom,'Message lands below HUD');
 await page.waitForFunction(()=>!arrivalText.querySelector('.pneuma-eye-scanline'));
 await page.evaluate(()=>game.settings.set('pneuma-combattools','eyeHUDAnimateMessages',false));
 assert.equal(await page.evaluate(()=>Array.from(document.querySelectorAll('.pneuma-eye-notification > :first-child')).some(t=>t.getAnimations().length)),false,'Disabling cancels active arrivals');
 await page.evaluate(()=>{moduleEntry.api.hud.list().forEach(n=>moduleEntry.api.hud.dismiss(n.source,n.id));moduleEntry.api.hud.send({source:'animation',id:'disabled',text:'Direct notice'});});
 await page.waitForFunction(()=>document.querySelector('.pneuma-eye-notification')?.textContent.includes('Direct notice'));
 assert.equal(await page.locator('.pneuma-eye-notification > :first-child').evaluate(t=>t.getAnimations().length),0);
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.evaluate(()=>{game.settings.set('pneuma-combattools','eyeHUDAnimateMessages',true);moduleEntry.api.hud.list().forEach(n=>moduleEntry.api.hud.dismiss(n.source,n.id));moduleEntry.api.hud.send({source:'animation',id:'reduced',text:'Reduced motion'});});
 await page.waitForFunction(()=>document.querySelector('.pneuma-eye-notification')?.textContent.includes('Reduced motion'));
 assert.equal(await page.locator('.pneuma-eye-notification > :first-child').evaluate(t=>t.getAnimations().length),0);
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.evaluate(()=>moduleEntry.api.hud.list().forEach(n=>moduleEntry.api.hud.dismiss(n.source,n.id)));
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-notification'));

 assert.equal(await page.locator('.pneuma-eye-conditions .pneuma-eye-condition').count(),1,'Prone must not appear as pathology');
 assert.equal(await page.locator('.pneuma-eye-situation').innerText(),'PRONE');
 assert.equal(await page.locator('.pneuma-eye-effect-arrival').count(),0,'Existing conditions establish baseline without announcements');
 await page.evaluate(()=>{
  window.beforeActivation=actor.allApplicableEffects;values.biomonitorFlashSeconds=0;
  actor.allApplicableEffects=()=>[...beforeActivation(),{name:'Boost Primary',statuses:new Set()},{name:'Poison',statuses:new Set(['poison'])}];
  hooks.updateActor.forEach(f=>f(actor));
 });
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-effect-arrival').length===2);
 assert.equal(await page.locator('#pneuma-eye-hud .is-arriving').count(),2,'Dashboard waits for announcement');
 const blink=await page.evaluate(()=>{
  const node=document.querySelector('.pneuma-eye-effect-arrival');
  window.effectAnimation=node.getAnimations()[0];effectAnimation.pause();
  return [850,1000,1180,1330,1520,1700].map(time=>{effectAnimation.currentTime=time;return getComputedStyle(node).opacity;});
 });
 assert.deepEqual(blink,['0','1','0','1','0','1'],'Three distinct off/on blinks');
 await page.evaluate(()=>hooks.updateActor.forEach(f=>f(actor)));
 await page.waitForTimeout(40);
 assert.equal(await page.evaluate(()=>document.querySelector('.pneuma-eye-effect-arrival').getAnimations()[0]===effectAnimation),true,'Refresh preserves current activation');
 await page.evaluate(()=>document.querySelectorAll('.pneuma-eye-effect-arrival').forEach(node=>node.getAnimations().forEach(a=>a.finish())));
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-effect-arrival'));
 assert.equal(await page.locator('#pneuma-eye-hud .is-arriving').count(),0,'Dashboard lights after sequence');
 await page.evaluate(()=>{actor.allApplicableEffects=beforeActivation;hooks.updateActor.forEach(f=>f(actor));});
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-drug-light'));
 await page.evaluate(()=>{actor.allApplicableEffects=()=>[...beforeActivation(),{name:'Boost Primary',statuses:new Set()}];hooks.updateActor.forEach(f=>f(actor));});
 await page.waitForSelector('.pneuma-eye-effect-arrival');
 await page.evaluate(()=>game.settings.set('pneuma-combattools','eyeHUDAnimateMessages',false));
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-effect-arrival'));
 assert.equal(await page.locator('#pneuma-eye-hud .is-arriving').count(),0,'Disable immediately releases dashboard');
 await page.evaluate(()=>{actor.allApplicableEffects=beforeActivation;hooks.updateActor.forEach(f=>f(actor));});
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-drug-light'));
 await page.evaluate(()=>game.settings.set('pneuma-combattools','eyeHUDAnimateMessages',true));

 assert.equal(await page.locator('#pneuma-eye-hud .pneuma-eye-alert').count(),0);
 assert.equal(await page.locator('.pneuma-eye-drug-light').count(),0);
 assert.equal(await page.locator('.pneuma-eye-drug-lights').isVisible(),false);
 assert.equal(await page.locator('.pneuma-eye-ekg + .pneuma-eye-vital-state').count(),1,'Wound label must immediately follow EKG');
 await page.evaluate(()=>{
  window.savedEffects=actor.allApplicableEffects;
  actor.allApplicableEffects=()=>['Black Lace Primary','Blue Glass','Boost Primary','Smash Primary','Synthcoke Addicted Primary','Berserker','Prime Time','Sixgun Addiction Primary','Timewarp Primary','Antibiotic','Stim','Surge','Quick Fix','Sedative','Veritas Primary'].map(name=>({name,statuses:new Set()}));
  hooks.updateActor.forEach(f=>f(actor));
 });
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-drug-light').length===15);
 assert.equal(await page.locator('.pneuma-eye-drug-light[data-kind=drug]').count(),9);
 assert.equal(await page.locator('.pneuma-eye-drug-light[data-kind=pharma]').count(),6);
 await page.evaluate(()=>{
  actor.allApplicableEffects=()=>[{name:'Veritas Primary',statuses:new Set()},{name:'Timewarp Addiction',statuses:new Set()},{name:'Berserker Addiction',statuses:new Set()},{name:'Sedative',disabled:true,statuses:new Set(['sedative'])}];
  hooks.updateActor.forEach(f=>f(actor));
 });
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-drug-light').length===1);
 assert.match(await page.locator('.pneuma-eye-drug-light').getAttribute('aria-label'),/Veritas/);
 const rowLeft=await page.locator('.pneuma-eye-drug-lights').boundingBox();
 const iconLeft=await page.locator('.pneuma-eye-drug-light').boundingBox();
 assert.equal(iconLeft.x,rowLeft.x,'Only Veritas still occupies the leftmost slot');
 assert.equal(await page.locator('.pneuma-eye-lamp[data-kind=addict]').count(),1,'Native supplemental addiction activates only the summary lamp');
 await page.evaluate(()=>{actor.allApplicableEffects=savedEffects;hooks.updateActor.forEach(f=>f(actor));});
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-drug-light'));
 assert.equal(await page.locator('.pneuma-eye-drug-lights').isVisible(),false);
 assert.equal(await page.locator('.pneuma-eye-notification').count(),0);
 assert.equal(await page.locator('#pneuma-eye-hud > .pneuma-eye-header').count(),0);
 assert.equal(await page.locator('.pneuma-eye-cyber-heading [aria-label="Minimize status HUD"]').count(),1);
 assert.equal(await page.locator('.pneuma-eye-identity').count(),0);
 await page.evaluate(()=>{
  window.effects=[{name:'Boost Primary',statuses:new Set()},{name:'Stim',statuses:new Set()},{name:'Synthcoke Addiction',statuses:new Set(['addiction'])},{name:'Sleep — Unconscious',statuses:new Set(['unconscious'])},{name:'Cover',statuses:new Set(['cover'])},{name:'Speed Heal',statuses:new Set(['speedheal'])},{name:'Netrunning',statuses:new Set(['netrunning'])}];
  actor.allApplicableEffects=()=>effects;
  hooks.updateActor.forEach(f=>f(actor));
 });
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-drug-light.is-on').length===2);
 assert.equal(await page.locator('.pneuma-eye-lamp[data-kind=addict].is-on').count(),1);
 assert.equal(await page.locator('.pneuma-eye-lamp[data-kind=unconscious].is-on').count(),1);
 assert.equal(await page.locator('.pneuma-eye-lamp[data-kind=jacked].is-on').count(),0,'Netrunning marker is not an active Jack-In');
 assert.doesNotMatch(await page.locator('.pneuma-eye-conditions').innerText(),/Boost|Stim|Speed|Addiction|Cover/);
 await page.evaluate(()=>{game.combat={started:true,flags:{'pneuma-combattools':{quickhackConnections:{a:{sourceActorUuid:actor.uuid,state:'active'}}}}};hooks.updateCombat.forEach(f=>f());});
 await page.waitForSelector('.pneuma-eye-lamp[data-kind=jacked].is-on');
 await page.evaluate(()=>{effects[0].disabled=true;effects[1].isSuppressed=true;hooks.updateActor.forEach(f=>f(actor));});
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-drug-light.is-on'));
 await page.evaluate(()=>{
  window.stableEKG=document.querySelector('.pneuma-eye-ekg');
  window.message={id:'attack',visible:true,isContentVisible:true,flags:{'pneuma-combattools':{exchange:{state:'waiting',defenderActor:actor.uuid,total:99,title:'SECRET'}}}};
  hooks.createChatMessage.forEach(f=>f(message));
 });
 await page.waitForSelector('.pneuma-eye-notification.is-attack');
 assert.equal(await page.evaluate(()=>stableEKG===document.querySelector('.pneuma-eye-ekg')),true,'Messages must not rebuild vitals');
 assert.equal(await page.locator('#pneuma-eye-hud .pneuma-eye-notification').count(),0);
 assert.doesNotMatch(await page.locator('#pneuma-eye-attachments').innerText(),/99|SECRET/);
 await page.getByRole('button',{name:'Incoming attack: open chat card',exact:true}).click();
 assert.equal(await page.evaluate(()=>openedChat),true);
 await page.evaluate(()=>{
  window.other={uuid:'Actor.other',name:'Vex',isOwner:false,system:{derivedStats:{hp:{value:12,max:40}}},items:[{type:'cyberware',name:'Biomonitor',system:{isInstalledInActor:true}}],allApplicableEffects:()=>[{name:'Hidden',statuses:new Set(['hidden'])}]};
  window.token={actor:other,isVisible:true,isPreview:false};canvas.activeLayer=canvas.tokens;
  hooks.hoverToken.forEach(f=>f(token,true));
 });
 await page.waitForFunction(()=>document.querySelector('.pneuma-eye-identity')?.textContent.includes('Vex · BIOMONITOR LINK'));
 assert.equal(await page.locator('.pneuma-eye-hp strong').innerText(),'12');
 assert.equal(await page.locator('.pneuma-eye-notification-owner').count(),0);
 assert.match(await page.locator('.pneuma-eye-notifications').getAttribute('aria-label'),/Smitty/);
 assert.equal(await page.locator('.pneuma-eye-notification').first().evaluate(n=>getComputedStyle(n).fontSize),'24px');
 assert.equal(await page.locator('.pneuma-eye-notification').first().evaluate(n=>getComputedStyle(n).color),'rgb(255, 180, 95)');
 assert.equal(await page.locator('.pneuma-eye-notification.is-attack').count(),1,'Own attack remains while viewing someone else');
 await page.evaluate(()=>hooks.hoverToken.forEach(f=>f(token,false)));
 await page.waitForFunction(()=>document.querySelector('#pneuma-eye-hud')?.getAttribute('aria-label').includes('Smitty'));
 await page.evaluate(()=>{other.items=[];hooks.hoverToken.forEach(f=>f(token,true));});
 await page.waitForTimeout(40);
 assert.match(await page.locator('#pneuma-eye-hud').getAttribute('aria-label'),/Smitty/,'No implant means no shared HUD');
 await page.evaluate(()=>{for(let i=0;i<5;i++)moduleEntry.api.hud.send({source:'test',id:String(i),text:'Notice '+i,duration:0});});
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-notification').length===3);
 assert.equal(await page.evaluate(()=>moduleEntry.api.hud.list().length),3);
 assert.equal(await page.evaluate(()=>moduleEntry.api.hud.list().every(n=>n.expires>Date.now())),true,'Ordinary messages expire even with legacy duration=0');
 await page.getByRole('button',{name:'Clear notification: Incoming Attack',exact:true}).click();
 assert.equal(await page.evaluate(()=>message.flags['pneuma-combattools'].exchange.state),'waiting','Dismiss does not resolve an attack');
 await page.evaluate(()=>{moduleEntry.api.hud.list().forEach(n=>moduleEntry.api.hud.dismiss(n.source,n.id));moduleEntry.api.hud.send({source:'test',id:'expiry',text:'Short notice',duration:.05});});
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-notification'));
 await page.evaluate(()=>{window.originalEffects=effects;effects=effects.filter(e=>e.name!=='Cover');hooks.updateActor.forEach(f=>f(actor));});
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-situation').length===0);
 const withoutStatus=await page.locator('#pneuma-eye-hud').boundingBox();
 await page.evaluate(()=>{effects=originalEffects;hooks.updateActor.forEach(f=>f(actor));});
 await page.evaluate(()=>{effects.push({name:'Prone',statuses:new Set(['prone'])});hooks.updateActor.forEach(f=>f(actor));});
 await page.waitForFunction(()=>document.querySelectorAll('.pneuma-eye-situation').length===2);
 assert.equal(await page.locator('#pneuma-eye-hud .pneuma-eye-situation').count(),2,'Statuses must be inside the HUD');
 const bounds=await page.locator('#pneuma-eye-hud').boundingBox();
 assert.equal(bounds.height,withoutStatus.height,'Floating statuses must not increase HUD height');
 assert.equal(bounds.width,withoutStatus.width,'Floating statuses must not increase HUD width');
 const dockBounds=await page.locator('.pneuma-eye-status-dock').boundingBox();
 assert.ok(dockBounds.y+dockBounds.height<=bounds.y+bounds.height,'Dock stays inside lower edge');
 const positions=await page.locator('.pneuma-eye-situation').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().x));
 assert.ok(positions[0]>positions[1],'Subsequent statuses extend left');
 await page.getByRole('button',{name:'Minimize status HUD',exact:true}).click();
 await page.waitForSelector('#pneuma-eye-hud.is-minimized');
 assert.equal(await page.locator('.pneuma-eye-status-dock').isVisible(),false);
 await page.getByRole('button',{name:'Expand status HUD',exact:true}).click();
 await page.waitForSelector('.pneuma-eye-medical');
 assert.equal(await page.getByRole('button',{name:'Minimize status HUD',exact:true}).count(),1,'Expand must not duplicate inline controls');
 const initial=await page.locator('#pneuma-eye-hud').boundingBox();
 await page.locator('.pneuma-eye-conditions .pneuma-eye-medical-label').hover();await page.mouse.down();await page.mouse.move(initial.x-40,initial.y+50);await page.mouse.up();
 assert.equal(await page.evaluate(()=>values.eyeHUDPosition),null,'Docking leaves saved drag position untouched');
 assert.deepEqual(await page.locator('#pneuma-eye-hud').boundingBox(),initial,'Dragging is inactive');
 async function assertDocked(){
  await page.waitForFunction(()=>{const h=document.getElementById('pneuma-eye-hud').getBoundingClientRect();const d=document.getElementById('sidebar').getBoundingClientRect();return Math.abs(h.right-(d.left-8))<1 && h.top===8;});
  const b=await page.locator('#pneuma-eye-hud').boundingBox();
  assert.ok(b.x>=7,'HUD fits available viewport');
  assert.ok(await page.locator('#pneuma-eye-attachments').evaluate(e=>e.getBoundingClientRect().right<=document.getElementById('sidebar').getBoundingClientRect().left-7),'Notifications stay outside dock');
 }
 await assertDocked();
 await page.evaluate(()=>document.getElementById('sidebar').style.width='32px');
 await assertDocked();
 await page.evaluate(()=>document.getElementById('sidebar').style.width='300px');
 await assertDocked();
 await page.setViewportSize({width:800,height:800});
 await assertDocked();
 await page.setViewportSize({width:1100,height:800});
 await assertDocked();
 await page.evaluate(()=>{const old=document.getElementById('sidebar');const next=old.cloneNode();next.style.width='260px';old.replaceWith(next);hooks.renderSidebar.forEach(f=>f());});
 await assertDocked();
 await page.evaluate(()=>{game.user.isGM=true;canvas.tokens.controlled=[{actor,name:'Smitty'}];hooks.controlToken.forEach(f=>f());});
 await page.waitForSelector('.pneuma-eye-identity');
 assert.equal(await page.locator('.pneuma-eye-identity').innerText(),'Smitty');
 const gmHUD=await page.locator('#pneuma-eye-hud').boundingBox();
 const gmName=await page.locator('.pneuma-eye-identity').boundingBox();
 assert.ok(gmName.y>=gmHUD.y+gmHUD.height,'GM name below the HUD');
 assert.ok(Math.abs(gmName.x-gmHUD.x)<2,'GM name aligned to left edge');
 await page.getByRole('button',{name:'Minimize status HUD',exact:true}).click();
 await page.waitForSelector('#pneuma-eye-hud.is-minimized');
 await assertDocked();
 const miniHUD=await page.locator('#pneuma-eye-hud').boundingBox();
 const miniName=await page.locator('.pneuma-eye-identity').boundingBox();
 assert.ok(Math.abs(miniName.x-miniHUD.x)<2,'Name follows minimized HUD left edge');
 assert.ok(miniName.y>=miniHUD.y+miniHUD.height,'Name remains below minimized HUD');
 assert.ok(Math.abs(miniName.width-miniHUD.width)<2,'Name width follows minimized HUD');
 await page.getByRole('button',{name:'Expand status HUD',exact:true}).click();
 await page.waitForSelector('.pneuma-eye-medical');
 const expandedHUD=await page.locator('#pneuma-eye-hud').boundingBox();
 const expandedName=await page.locator('.pneuma-eye-identity').boundingBox();
 assert.ok(Math.abs(expandedName.x-expandedHUD.x)<2,'Name returns to expanded HUD left edge');
 assert.equal(await page.locator('#pneuma-eye-hud > .pneuma-eye-header').count(),0);

 await page.evaluate(()=>game.settings.set('pneuma-combattools','eyeHUD',false));
 await page.waitForFunction(()=>!document.getElementById('pneuma-eye-hud')&&!document.getElementById('pneuma-eye-attachments'));
 if (shortcutSource) {
 await page.evaluate(()=>{
   const hud=document.createElement('div');hud.id='pneuma-crewtools-calendar';
   hud.innerHTML='<span class="pneuma-calendar-date"><span class="pneuma-calendar-weekday">Wednesday</span><span class="pneuma-calendar-month-day">Sep 23</span><span class="pneuma-calendar-year">2045</span></span><div class="pneuma-crew-hud"><button aria-label="Crew">♟</button></div>';
   document.body.append(hud);refreshHudShortcuts();
   for(const [id,css] of [['navigation','position:fixed;left:110px;top:0;width:650px;height:90px'],['controls','position:fixed;left:0;top:100px;width:100px;height:400px']]){const node=document.createElement('div');node.id=id;node.style.cssText=css;document.body.append(node);}
   moduleEntry.api.hud.list().forEach(n=>moduleEntry.api.hud.dismiss(n.source,n.id));
   values.eyeHUDMessage=null;game.messages=[];actor.system.derivedStats.hp.value=9;
   game.settings.set('pneuma-combattools','eyeHUD',true);
   game.settings.set('pneuma-combattools','eyeHUDMinimized',false);
   game.settings.set('pneuma-combattools','crewHUDIntegration',true);
 });
 await page.waitForSelector('#pneuma-crewtools-calendar #pneuma-biomon-shortcut');
 assert.equal(await page.locator('#pneuma-biomon-shortcut').count(),1,'Enabling immediately registers the button even while expanded');
 const crewBox=await page.getByRole('button',{name:'Crew',exact:true}).boundingBox();
 const bioBox=await page.locator('#pneuma-biomon-shortcut').boundingBox();
 assert.ok(bioBox.y>=crewBox.y+crewBox.height && Math.abs(bioBox.x-crewBox.x)<1,'Biomon sits below Crew in the same column');
 assert.equal(Math.round((await page.locator('#pneuma-crewtools-calendar').boundingBox()).width),138,'Calendar does not widen');
 assert.equal(await page.locator('#pneuma-biomon-shortcut').evaluate(b=>getComputedStyle(b).color),'rgb(255, 98, 98)');
 await page.getByRole('button',{name:'Minimize Biomon',exact:true}).click();
 await page.waitForSelector('#pneuma-eye-hud.is-integrated-mini');
 await page.evaluate(()=>moduleEntry.api.hud.send({source:'integration',id:'alert',text:'Incoming hack'}));
 await page.waitForFunction(()=>document.querySelector('#pneuma-biomon-shortcut').classList.contains('has-alert'));
 assert.equal(await page.locator('#pneuma-biomon-shortcut').evaluate(b=>getComputedStyle(b).color),'rgb(255, 180, 95)');
 assert.equal(await page.locator('#pneuma-eye-hud .pneuma-biomon-icon').count(),0,'Integrated EKG has no bell');
 assert.equal(await page.locator('#pneuma-biomon-shortcut .pneuma-biomon-icon').count(),1,'Crew shortcut uses approved heart and bell');
 assert.equal(await page.locator('.pneuma-eye-identity').textContent(),'Smitty');
 const rightMini=await page.locator('#pneuma-eye-hud').boundingBox();
 assert.ok(rightMini.x>400,'Right docking is retained when integrated');
 await page.evaluate(()=>game.settings.set('pneuma-combattools','eyeHUDAnimateMessages',false));
 await page.screenshot({path:process.env.TEMP+'/pneuma-integrated-mini.png'});
 await page.evaluate(()=>game.settings.set('pneuma-combattools','eyeHUDDock','left'));
 await page.waitForFunction(()=>document.querySelector('#pneuma-eye-hud').getBoundingClientRect().left<200);
 const miniLeft=await page.locator('#pneuma-eye-hud').boundingBox();
 const miniMessages=await page.locator('#pneuma-eye-attachments').boundingBox();
 assert.ok(miniMessages.width>miniLeft.width*2,'Minimized messages extend beyond EKG width');
 assert.ok(Math.abs(miniMessages.x-miniLeft.x)<1,'Messages remain left-aligned below EKG');
 await page.screenshot({path:process.env.TEMP+'/pneuma-minimized-wide-messages.png'});
 await page.getByRole('button',{name:'Open Biomon',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('#pneuma-eye-hud').classList.contains('is-minimized'));
 const left=await page.locator('#pneuma-eye-hud').boundingBox();
 const crewAnchor=await page.locator('#pneuma-crewtools-calendar').boundingBox();
 assert.ok(Math.abs(left.x-crewAnchor.x-crewAnchor.width-8)<1 && Math.abs(left.y-crewAnchor.y-crewAnchor.height-8)<1,'Expanded panel anchors diagonally below Crew HUD');
 assert.ok(Math.abs(miniLeft.x-left.x)<1 && Math.abs(miniLeft.y-left.y)<1,'Minimized EKG and expanded HUD share the same anchor');
 const notice=page.locator('.pneuma-eye-notification').first();
 const clearBox=await notice.locator(':scope > :last-child').boundingBox();
 const textBox=await notice.locator(':scope > :first-child').boundingBox();
 assert.ok(clearBox.x<textBox.x && clearBox.y>=left.y+left.height,'X comes first below HUD');
 assert.equal(await notice.locator(':scope > :first-child').evaluate(e=>getComputedStyle(e).textAlign),'left');
 assert.equal(await page.locator('#pneuma-biomon-shortcut').count(),1,'Shortcut persists while expanded');
 await page.screenshot({path:process.env.TEMP+'/pneuma-integrated-expanded.png'});
 await page.evaluate(()=>game.settings.set('pneuma-combattools','eyeHUD',false));
 await page.waitForSelector('#pneuma-eye-hud',{state:'detached'});
 await page.getByRole('button',{name:'Open Biomon',exact:true}).click();
 await page.waitForSelector('#pneuma-eye-hud',{state:'visible'});
 await page.getByRole('button',{name:'Minimize Biomon',exact:true}).click();
 await page.waitForSelector('#pneuma-eye-hud.is-integrated-mini');
 await page.evaluate(()=>{document.getElementById('pneuma-crewtools-calendar').remove();refreshHudShortcuts();});
 await page.waitForFunction(()=>!document.querySelector('#pneuma-eye-hud')?.classList.contains('is-integrated-mini'));
 assert.equal(await page.locator('.is-integrated-mini').count(),0,'Hidden Crew HUD restores standalone control');
 await page.evaluate(()=>{const root=document.createElement('div');root.id='pneuma-crewtools-calendar';document.body.append(root);refreshHudShortcuts();});
 await page.waitForSelector('#pneuma-biomon-shortcut');
 await page.evaluate(()=>game.settings.set('pneuma-combattools','crewHUDIntegration',false));
 await page.waitForSelector('#pneuma-biomon-shortcut',{state:'detached'});
 assert.equal(await page.locator('[data-shortcut-owner]').count(),0,'Opting out removes the registered slot');
 } else console.log('Crew Tools integration checks skipped: set PNEUMA_CREWTOOLS_ROOT to its checkout.');
 await page.evaluate(()=>{
   game.settings.set('pneuma-combattools','crewHUDIntegration',false);
   game.settings.set('pneuma-combattools','eyeHUD',true);
   game.settings.set('pneuma-combattools','eyeHUDMinimized',true);
   game.settings.set('pneuma-combattools','eyeHUDDock','left');
 });
 await page.waitForFunction(()=>{const b=document.querySelector('#pneuma-eye-hud')?.getBoundingClientRect();const c=window.hudShortcuts?.getBounds();return b && (c ? Math.abs(b.x-c.right-8)<1 && Math.abs(b.y-c.bottom-8)<1 : b.x>=108 && b.y>=80);});
 assert.equal(await page.locator('#pneuma-eye-hud .pneuma-biomon-icon').count(),1,'Standalone left HUD uses the same composite icon');
 assert.equal(await page.evaluate(()=>settings.eyeHUDDock.config),true,'Position setting is always exposed');
 await page.getByRole('button',{name:'Expand status HUD',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('#pneuma-eye-hud').classList.contains('is-minimized'));
 const standaloneLeft=await page.locator('#pneuma-eye-hud').boundingBox();
 if (shortcutSource) {
   const anchor=await page.locator('#pneuma-crewtools-calendar').boundingBox();
   assert.equal(standaloneLeft.x,anchor.x+anchor.width+8);
   assert.equal(standaloneLeft.y,anchor.y+anchor.height+8);
   await page.evaluate(()=>game.settings.set('pneuma-combattools','crewHUDIntegration',true));
   await page.waitForSelector('#pneuma-biomon-shortcut');
   const integratedLeft=await page.locator('#pneuma-eye-hud').boundingBox();
   assert.equal(integratedLeft.x,standaloneLeft.x,'Integration does not change horizontal placement');
   assert.equal(integratedLeft.y,standaloneLeft.y,'Integration does not change vertical placement');
   await page.evaluate(()=>game.settings.set('pneuma-combattools','crewHUDIntegration',false));
   await page.waitForSelector('#pneuma-biomon-shortcut',{state:'detached'});
 }
 await page.screenshot({path:process.env.TEMP+'/pneuma-standalone-top-left.png'});
 await page.evaluate(()=>game.settings.set('pneuma-combattools','eyeHUDDock','right'));
 await page.waitForFunction(()=>document.querySelector('#pneuma-eye-hud').getBoundingClientRect().x>8);

 await page.evaluate(()=>{
  game.settings.set('pneuma-combattools','eyeHUD',true);
  game.settings.set('pneuma-combattools','eyeHUDAnimateMessages',false);
  moduleEntry.api.hud.list().forEach(n=>moduleEntry.api.hud.dismiss(n.source,n.id));
  moduleEntry.api.hud.send({source:'delivery',id:'flash',text:'Dramatic only',mode:'flash'});
 });
 await page.waitForSelector('.pneuma-hud-flash');
 assert.equal(await page.evaluate(()=>moduleEntry.api.hud.list().length),0,'Flash has no queue entry');
 assert.equal(await page.locator('.pneuma-hud-flash button').count(),0);
 await page.waitForSelector('.pneuma-hud-flash',{state:'detached',timeout:6000});
 assert.equal(await page.locator('#pneuma-hud-flashes').count(),0,'Expired flashes remove their empty container');
 await page.evaluate(()=>{
  game.settings.set('pneuma-combattools','eyeHUDAnimateMessages',true);
  moduleEntry.api.hud.send({source:'delivery',id:'animated',text:'Netrunner detected',mode:'flash'});
 });
 assert.equal(await page.locator('.pneuma-hud-flash').evaluate(e=>e.getAnimations().length),1);
 await page.locator('.pneuma-hud-flash').evaluate(e=>{const a=e.getAnimations()[0];a.pause();a.currentTime=1000;});
 await page.screenshot({path:process.env.TEMP+'/pneuma-flash-alert.png'});
 await page.evaluate(()=>moduleEntry.api.hud.dismiss('delivery','animated'));
 assert.equal(await page.locator('.pneuma-hud-flash').count(),0);
 await page.evaluate(()=>moduleEntry.api.hud.send({source:'delivery',id:'queued',text:'Keep until cleared',mode:'queued',duration:1}));
 await page.waitForFunction(()=>document.querySelector('.pneuma-eye-notifications')?.textContent.includes('Keep until cleared'));
 await page.waitForTimeout(1100);
 assert.equal(await page.evaluate(()=>moduleEntry.api.hud.list().find(n=>n.id==='queued').expires),0);
 await page.getByRole('button',{name:'Clear notification: Keep until cleared',exact:true}).click();
 assert.equal(await page.evaluate(()=>moduleEntry.api.hud.list().length),0);
 await page.evaluate(()=>{
  game.user.isGM=false;
  game.settings.set('pneuma-combattools','eyeHUDAnimateMessages',false);
  const form=document.createElement('div');form.id='animation-setting-test';form.innerHTML='<div class="form-group"><input name="pneuma-combattools.eyeHUDAnimateMessages"></div>';document.body.append(form);
  game.settings.set('pneuma-combattools','forcePlayerHUDAnimations',true);
  hooks.renderSettingsConfig.forEach(fn=>fn({},[form]));
  moduleEntry.api.hud.send({source:'forced',id:'player',text:'Forced player animation',mode:'flash'});
 });
 assert.equal(await page.evaluate(()=>settings.forcePlayerHUDAnimations.scope),'world');

 assert.equal(await page.locator('#animation-setting-test .form-group').evaluate(e=>e.hidden),true);
 assert.equal(await page.locator('.pneuma-hud-flash').evaluate(e=>e.getAnimations().length),1);
 await page.evaluate(()=>{
  moduleEntry.api.hud.dismiss('forced','player');game.user.isGM=true;
  hooks.renderSettingsConfig.forEach(fn=>fn({},[document.getElementById('animation-setting-test')]));
  moduleEntry.api.hud.send({source:'forced',id:'gm',text:'GM preference',mode:'flash'});
 });
 assert.equal(await page.locator('#animation-setting-test .form-group').evaluate(e=>e.hidden),false);
 assert.equal(await page.locator('.pneuma-hud-flash').evaluate(e=>e.getAnimations().length),0);
 await page.evaluate(()=>{
  moduleEntry.api.hud.dismiss('forced','gm');game.user.isGM=false;
  game.settings.set('pneuma-combattools','forcePlayerHUDAnimations',false);
  moduleEntry.api.hud.send({source:'forced',id:'restored',text:'Player preference restored',mode:'flash'});
 });
 assert.equal(await page.locator('#animation-setting-test .form-group').evaluate(e=>e.hidden),false);
 assert.equal(await page.locator('.pneuma-hud-flash').evaluate(e=>e.getAnimations().length),0);
 assert.equal(await page.evaluate(()=>values.eyeHUDAnimateMessages),false);
 await page.evaluate(()=>{moduleEntry.api.hud.dismiss('forced','restored');document.getElementById('animation-setting-test').remove();});
 await page.evaluate(()=>{
   game.user.character=actor;canvas.tokens.controlled=[];
   values.eyeHUDMinimized=false;values.eyeHUD=true;
   window.testIncoming=[{messageId:'intruder',name:'Unknown Netrunner'}];
   hooks.updateCombat.forEach(fn=>fn({},{}));
 });
 await page.waitForSelector('.pneuma-eye-lamp[data-kind="intrusion"]');
 assert.equal(await page.locator('.pneuma-eye-lamp[data-kind="intrusion"]').innerText(),'NEURAL INTRUSION');
 assert.equal(await page.locator('.pneuma-eye-situation').filter({hasText:'Incoming Jack-In'}).count(),0);
 await page.screenshot({path:process.env.TEMP+'/pct-neural-intrusion.png'});
 await page.evaluate(()=>{window.testIncoming=[];hooks.updateCombat.forEach(fn=>fn({},{}));});
 await page.waitForFunction(()=>!document.querySelector('.pneuma-eye-lamp[data-kind="intrusion"]'));
 await page.evaluate(()=>{values.eyeHUDDock='right';values.combatBarDock='top-right';hooks.pneumaCombatBarDockChanged.forEach(fn=>fn());});
 await page.waitForFunction(()=>document.getElementById('pneuma-eye-hud').getBoundingClientRect().left<innerWidth/2);
 assert.equal(await page.evaluate(()=>values.eyeHUDDock),'right','Combat bar does not overwrite saved Biomon dock');
 await page.evaluate(()=>{values.combatBarDock='bottom-left';hooks.pneumaCombatBarDockChanged.forEach(fn=>fn());});
 console.log('GM animation enforcement passed: player override, hidden setting, GM exemption and restored preference.');
 console.log('HUD delivery modes passed: flash animation, static fallback, expiry, queue and dismissal.');
 console.log('HUD browser regression passed: classification, native drugs, sharing, private messages, expiry, docking and drag.');
}finally{await browser.close();}
