import assert from "node:assert/strict";
import {test} from "node:test";
import {registerHooks} from "node:module";
const get=(o,p)=>p.split('.').reduce((v,k)=>v?.[k],o),set=(o,p,v)=>{const keys=p.split('.');for(const k of keys.slice(0,-1))o=o[k]??={};o[keys.at(-1)]=v;};
registerHooks({resolve(s,c,next){if(s==="/systems/cyberpunk-red-core/modules/extern/cpr-dice-handler.js")return {shortCircuit:true,url:'data:text/javascript,export default {handle3dDice:async(r,mode)=>globalThis.diceModes.push(mode)}'};return next(s,c);}});
globalThis.FormApplication=class{};globalThis.foundry={utils:{getProperty:get,setProperty:set,deepClone:structuredClone,randomID:()=>String(++serial)}};
let serial=0;
class Collection extends Map {[Symbol.iterator](){return this.values()}filter(fn){return [...this.values()].filter(fn)}find(fn){return [...this.values()].find(fn)}some(fn){return [...this.values()].some(fn)}}
class Doc {constructor(data,parent){Object.assign(this,data);this.id=data._id??String(++serial);this.parent=parent;this.effects=new Collection();this.statuses=new Set(data.statuses??[])}async update(changes){for(const [k,v] of Object.entries(changes))set(this,k,v);return this}}
class Actor extends Doc {constructor(){super({name:'Target',type:'character',system:{derivedStats:{hp:{value:40}},stats:{luck:{value:3}}}});this.uuid='Actor.'+this.id;this.items=new Collection();this.effects=new Collection();this.isOwner=true}testUserPermission(u){return u.id==='owner'}async createEmbeddedDocuments(type,rows){if(this.failCreate)throw Error('write failed');return rows.map(r=>{const d=new Doc(r,this);(type==='Item'?this.items:this.effects).set(d.id,d);return d})}async deleteEmbeddedDocuments(type,ids){for(const id of ids)(type==='Item'?this.items:this.effects).delete(id)}async updateEmbeddedDocuments(type,rows){for(const row of rows)await (type==='Item'?this.items:this.effects).get(row._id).update(row)}async toggleStatusEffect(id){if(!this.effects.some(e=>e.statuses.has(id)))await this.createEmbeddedDocuments('ActiveEffect',[{statuses:[id]}])}}
globalThis.Actor=Actor;globalThis.Item=Doc;
const {masterStatuses}=await import('../dist/scripts/status-catalog.js');
const {instantEffects,ammoProfile}=await import('../dist/scripts/instant-catalog.js');
const {handleInstant,newInstant,instantContent}=await import('../dist/scripts/instant-effects.js');
const {temporaryInjury,expireInstantActor,sleepTarget,clearInstantCondition,igniteTarget,burnTurn,registerInstantLifetimes}=await import('../dist/scripts/instant-lifetime.js');
const {damageStatusChoices,validateDamageStatuses}=await import('../dist/scripts/damage-status.js');
function setup(){
 const gm={id:'gm',isGM:true,active:true},owner={id:'owner',isGM:false,active:true},actor=new Actor();
 globalThis.game={user:gm,users:new Collection([[gm.id,gm],[owner.id,owner]]),time:{worldTime:100},settings:{get:()=>''},i18n:{localize:s=>s},actors:[actor],scenes:[],combats:new Map(),packs:{get:pack=>({getDocument:async id=>{const s=masterStatuses.find(s=>s.binding?.pack===pack&&s.binding.itemId===id);return {toObject:()=>({_id:id,name:s.name,type:'criticalInjury',effects:[],system:{}})}}})}};
 globalThis.fromUuid=async uuid=>uuid===actor.uuid?actor:null;globalThis.CONFIG={statusEffects:[{id:'prone',name:'Prone'}]};globalThis.diceModes=[];
 globalThis.Roll=class {constructor(formula){this.formula=formula}async evaluate(){this.total=this.formula==='3d6'?12:8;return this}async render(){return '<div>'+this.total+'</div>'}};
 globalThis.ui={notifications:{error:m=>{throw Error(m)}}};globalThis.hooks={};globalThis.Hooks={on:(n,f)=>{(hooks[n]??=[]).push(f)},once:(n,f)=>{(hooks[n]??=[]).push(f)}};
 let saves=0;return {actor,gm,owner,save:async()=>{saves++},saves:()=>saves};
}
async function resist(f,id,total){const s=newInstant(id,f.actor.uuid,f.actor.name);await handleInstant(s,{action:'claim',nonce:'n'},f.owner,f.save);await handleInstant(s,{action:'commit',nonce:'n',total,html:'<div>native</div>'},f.owner,f.save);return s}
test('eligibility is nine grenade types, two rocket types; no basic/expansive/rubber',()=>{
 const ids=['armorPiercing',...Object.keys(instantEffects),'smart'];assert.equal(ids.filter(id=>ammoProfile(id,'grenade')).length,9);assert.deepEqual(ids.filter(id=>ammoProfile(id,'rocket')),['armorPiercing','smart']);for(const id of ['basic','rubber','expansive'])assert.equal(ammoProfile(id,'grenade'),undefined);
});
test('resistance must beat DV; tied poison check fails, higher check resists',async()=>{const f=setup();assert.equal((await resist(f,'poison',13)).state,'failed');const s=await resist(f,'poison',14);await handleInstant(s,{action:'apply'},f.owner,f.save);assert.equal(s.state,'resisted');assert.equal(f.actor.system.derivedStats.hp.value,40)});
test('poison and biotoxin bypass armor, roll once, and do not apply twice',async()=>{for(const [id,amount] of [['poison',8],['biotoxin',12]]){const f=setup();f.actor.armor=11;const s=await resist(f,id,0);await handleInstant(s,{action:'apply'},f.owner,f.save,'blindroll');await handleInstant(s,{action:'apply'},f.owner,f.save);assert.equal(f.actor.system.derivedStats.hp.value,40-amount);assert.equal(f.actor.armor,11);assert.deepEqual(diceModes,['blindroll']);assert.equal(s.state,'applied')}});
test('unowned targets, other users reservations, and non-GM immunity skips are rejected',async()=>{const f=setup(),s=newInstant('poison',f.actor.uuid,'T');await assert.rejects(handleInstant(s,{action:'claim',nonce:'n'},{id:'stranger'},f.save),/owner/);await handleInstant(s,{action:'claim',nonce:'n'},f.owner,f.save);await assert.rejects(handleInstant(s,{action:'commit',nonce:'n',total:30,html:''},f.gm,f.save),/reservation/);await handleInstant(s,{action:'reset'},f.gm,f.save);await assert.rejects(handleInstant(s,{action:'skip'},f.owner,f.save),/GM/);await handleInstant(s,{action:'skip'},f.gm,f.save);assert.equal(s.state,'skipped')});
test('failed application requires GM review; retry never repeats target writes',async()=>{const f=setup(),s=await resist(f,'flashbang',0);f.actor.failCreate=true;await assert.rejects(handleInstant(s,{action:'apply'},f.owner,f.save),/write failed/);assert.equal(s.state,'review');await assert.rejects(handleInstant(s,{action:'apply'},f.owner,f.save),/resistance/);await handleInstant(s,{action:'review'},f.gm,f.save);assert.equal(s.state,'applied')});
test('flashbang applies two native injuries with no HP damage; tear gas only eye',async()=>{for(const [id,n] of [['flashbang',2],['teargas',1]]){const f=setup(),s=await resist(f,id,0);await handleInstant(s,{action:'apply'},f.owner,f.save);assert.equal(f.actor.items.size,n);assert.equal(f.actor.system.derivedStats.hp.value,40);assert.ok(f.actor.items.filter(i=>get(i,'flags.pneuma-combattools.instantLifetime.expires')===160).length===n)}});
test('temporary injury expiry preserves permanent injuries and extends repeated temporary exposure',async()=>{const f=setup();await f.actor.createEmbeddedDocuments('Item',[{name:'Damaged Ear',type:'criticalInjury'}]);await temporaryInjury(f.actor,'Damaged Ear');assert.equal(get([...f.actor.items][0],'flags.pneuma-combattools.instantLifetime'),undefined);await temporaryInjury(f.actor,'Damaged Eye');game.time.worldTime=120;await temporaryInjury(f.actor,'Damaged Eye');await expireInstantActor(f.actor,160);assert.equal(f.actor.items.size,2);await expireInstantActor(f.actor,180);assert.equal(f.actor.items.size,1);assert.equal([...f.actor.items][0].name,'Damaged Ear')});
test('sleep waking and expiry preserve prone and pre-existing unconsciousness',async()=>{const f=setup();await sleepTarget(f.actor);await clearInstantCondition(f.actor,'sleep');assert.equal(f.actor.effects.size,1);assert.ok([...f.actor.effects][0].statuses.has(masterStatuses.find(s=>s.name==='Prone').id));await f.actor.createEmbeddedDocuments('ActiveEffect',[{statuses:[masterStatuses.find(s=>s.name==='Unconscious').id]}]);await sleepTarget(f.actor);await expireInstantActor(f.actor,1000);assert.equal(f.actor.effects.size,2)});
test('incendiary cannot stack and applies only once per ended turn; extinguishing stops it',async()=>{const f=setup();await igniteTarget(f.actor);await igniteTarget(f.actor);assert.equal(f.actor.effects.size,1);await burnTurn(f.actor,'c:1:0');await burnTurn(f.actor,'c:1:0');assert.equal(f.actor.system.derivedStats.hp.value,38);await burnTurn(f.actor,'c:2:0');assert.equal(f.actor.system.derivedStats.hp.value,36);await clearInstantCondition(f.actor,'fire');await burnTurn(f.actor,'c:3:0');assert.equal(f.actor.system.derivedStats.hp.value,36)});
test('EMP is gated on started combat before claiming application',async()=>{const f=setup(),s=await resist(f,'emp',0);await assert.rejects(handleInstant(s,{action:'apply'},f.owner,f.save),/Start combat/);assert.equal(s.state,'failed')});
test('Add effects exposes reusable instant effects and retains normal status choices',()=>{setup();assert.ok(damageStatusChoices().some(s=>s.id==='instant:poison'));assert.deepEqual(validateDamageStatuses(['instant:smoke','instant:flashbang','prone']),['instant:smoke','instant:flashbang','prone']);assert.throws(()=>validateDamageStatuses(['instant:unknown']),/available/);assert.throws(()=>validateDamageStatuses(['instant:poison','instant:poison']),/duplicated/)});
test('HP loss wakes module sleep without standing target up',async()=>{const f=setup();registerInstantLifetimes();await sleepTarget(f.actor);hooks.preUpdateActor[0](f.actor);f.actor.system.derivedStats.hp.value--;hooks.updateActor[0](f.actor);await new Promise(r=>setTimeout(r,0));assert.equal(f.actor.effects.size,1)});
test('effect names and scope attributes are escaped',()=>{setup();const s=newInstant('poison','a','T');assert.match(instantContent(s,'"<unsafe>'),/&quot;&lt;unsafe&gt;/)});

test('remote HP loss wakes Sleep without a local preUpdate hook',async()=>{const f=setup();registerInstantLifetimes();await sleepTarget(f.actor);f.actor.system.derivedStats.hp.value-=3;hooks.updateActor[0](f.actor);await new Promise(r=>setTimeout(r,0));assert.equal(f.actor.effects.size,1);assert.ok([...f.actor.effects][0].statuses.has(masterStatuses.find(s=>s.name==='Prone').id))});
test('remote combat advance burns the previous actor once without local preUpdate',async()=>{const f=setup();registerInstantLifetimes();await igniteTarget(f.actor);const c={id:'c',started:true,round:1,turn:0,combatant:{actor:f.actor}};hooks.createCombat[0](c);c.turn=1;c.combatant={actor:null};hooks.updateCombat[0](c);await new Promise(r=>setTimeout(r,0));assert.equal(f.actor.system.derivedStats.hp.value,38);hooks.updateCombat[0](c);await new Promise(r=>setTimeout(r,0));assert.equal(f.actor.system.derivedStats.hp.value,38)});
