import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {chromium}=await import(process.env.PNEUMA_PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({channel:'msedge',headless:true});
try {
 const page=await browser.newPage({viewport:{width:450,height:800}});
 await page.setContent('<main><div id="chat-controls"><i class="fa-dice-d20"></i></div><div id="cards"></div></main>');
 await page.addStyleTag({content:await readFile('dist/styles/pneuma-combattools.css','utf8')});
 await page.addStyleTag({content:'body{background:#ddd;font:14px Arial;padding:12px} .rollcard{padding:8px;border:1px solid #888;margin:8px 0} button{cursor:pointer} h3{margin:4px 0}'});
 await page.evaluate(()=>{
  window.hooks={};window.Hooks={on:(k,f)=>(hooks[k]??=[]).push(f),once:()=>{}};
  window.game={system:{id:'cyberpunk-red-core'},user:{id:'gm',isGM:true,active:true},settings:{get:()=>false},i18n:{localize:k=>k}};
  const gm=game.user,p1={id:'p1',isGM:false,active:true,name:'Player 1'},p2={id:'p2',isGM:false,active:true,name:'Player 2'};
  game.users=[gm,p1,p2];game.users.get=id=>game.users.find(u=>u.id===id);game.messages=new Map();
  window.actor={isOwner:true,uuid:'Actor.1',name:'Pex',items:[],testUserPermission:u=>u.id==='p1'||u.isGM};
  window.fromUuid=async id=>id.startsWith("Token.")?{uuid:id,actor}:actor;
  window.foundry={utils:{deepClone:o=>structuredClone(o),getProperty:(o,p)=>p.split('.').reduce((v,k)=>v?.[k],o),randomID:()=>Math.random().toString(36)}};
  window.ui={notifications:{error:message=>{throw Error(message)},warn:()=>{}},chat:{updateMessage:()=>{}}};
  window.Dialog=class {constructor(data){window.dialog=data;}render(){return this;}static async prompt(data){window.promptData=data;}};
  window.ChatMessage={getSpeaker:()=>({}),applyRollMode:()=>{},create:async data=>{window.created=data;return data;}};
  window.wrap=nodes=>({length:nodes.length,find:s=>wrap(nodes.flatMap(n=>[...n.querySelectorAll(s)])),prop:(k,v)=>{nodes.forEach(n=>n[k]=v);return wrap(nodes);},attr:(k,v)=>{nodes.forEach(n=>n.setAttribute(k,v));return wrap(nodes);},append:n=>nodes[0]?.append(n),on:(event,fn)=>nodes.forEach(n=>n.addEventListener(event,fn))});
  window.$=node=>wrap([node]);
  window.requireCombatSocket=()=>{};window.canRenderCombatCard=()=>true;
  window.damageContent=ex=>'<div class="pneuma-damage-result">'+ex.damage.result.html+halfArmorControl(ex.damage.result.values.ignorePercent,ex.damage.result.values.interactArmor!==false)+'<div class="pneuma-damage-application"><div class="pneuma-damage-application-box"></div></div></div>';
  window.validateDamageStatuses=effects=>effects??[];window.damageStatusChoices=()=>[];window.chooseDamageStatuses=async()=>['prone'];
  window.selectedDamageTarget=()=> 'Token.1';window.handleDamage=async(req,user,ex,save)=>{window.applied=req;await save();};
  window.applyFromCard=async(ex,send,shift,target,application,halfArmor)=>send('damageApply',{targetUuid:target,halfArmor});
  window.DiceHandler={handle3dDice:async()=>{}};window.LOGGER={debug:()=>{}};
  window.SystemUtils={Localize:k=>k,getUserTargetedOrSelected:()=>[]};
  window.facesQueue=[];
  window.Roll=class {constructor(formula){this.formula=formula;this._formula=formula;}async evaluate(){const faces=facesQueue.shift();if(!faces)throw Error('Unexpected extra dice');this.total=faces.reduce((a,b)=>a+b,0)+Number(/[+-]\d+$/.exec(this.formula)?.[0]??0);this.terms=[{formula:this.formula,total:this.total,faces:Number(this.formula.split('d')[1]),results:faces.map(result=>({result}))}];this.dice=this.terms;return this;}async render(){return '<div class="dice-roll">'+this.formula+' = '+this.total+'</div>';}static fromJSON(s){return JSON.parse(s)}};
  window.rollHidden=roll=>roll.roll();window.diceJSON=()=>[];window.nativeAPI=async()=>({Dice:DiceHandler});window.spendBonusLuck=async()=>{};
  window.nativeCard=async roll=>{window.lastRoll=roll;return '<div class="rollcard"><h3>'+roll.rollTitle+'</h3><b>'+roll.resultTotal+'</b></div>';};
  window.damageValues=()=>({total:12,bonus:0,location:'body',ignorePercent:lastRoll.rollCardExtraArgs.ignoreArmorPercent,ablation:lastRoll.rollCardExtraArgs.ablationValue});
  window.damageSixes=roll=>roll.faces.filter(n=>n===6).length;
 });
 const nativeRoot=process.env.TEMP+'/crewtools-cpr-native/fvtt-cyberpunk-red-core-v0.92.4-75b8c9d7cb76ed1ea2797a3404ce77172d424b6b/src';
 const native=await readFile(nativeRoot+'/modules/rolls/cpr-rolls.js','utf8');
 await page.addScriptTag({type:'module',content:native.replace(/^import .*$/gm,'')+'\nwindow.manualNativeClasses={CPRRoll,CPRDamageRoll,CPRTableRoll};'});
 for(const [file,names] of [['half-armor','armorIgnorePercent,halfArmorControl,halfArmorSelected,interactArmorSelected,bindHalfArmor,registerHalfArmor'],['manual-roll-state','MANUAL_MODULE,manualEscape,manualNumber,groupOutcome,groupContent']]) {
  const code=await readFile('dist/scripts/'+file+'.js','utf8');await page.addScriptTag({type:'module',content:code+'\nObject.assign(window,{'+names+'});'});
 }
 await page.waitForFunction(()=>window.groupContent&&window.manualNativeClasses);
 const sharedDamage=await readFile('dist/scripts/damage-flow.js','utf8');
 await page.addScriptTag({type:'module',content:'const retry=new Map();'+sharedDamage.slice(sharedDamage.indexOf('export async function renderDamage('))+'\nwindow.renderDamage=renderDamage;'});
 let code=await readFile('dist/scripts/manual-rolls.js','utf8');
 code=code.replace(/^import .*$/gm,'').replace('return await import(path);','return window.manualNativeClasses;').replace('(await import(path)).default','window.nativeUtils');
 await page.addScriptTag({type:'module',content:'const M=MANUAL_MODULE,esc=manualEscape;\n'+code+'\nObject.assign(window,{manualContent,handleManualRequest,bindManualCard,registerManualRolls,openManualRolls,damagePrompt,basePrompt,groupPrompt,criticalPrompt,statPrompt});'});
 await page.waitForFunction(()=>window.handleManualRequest);
 const result=await page.evaluate(async()=>{
  const check=(b,m)=>{if(!b)throw Error(m)};
  check(groupOutcome(13,13)==='Fail'&&groupOutcome(14,13)==='Success'&&groupOutcome(2)==='', 'DV comparisons');
  for(const n of [1,3,11,12])check(Math.round(n*(1-armorIgnorePercent(0,true)/100))===Math.ceil(n/2),'round upward');
  check(armorIgnorePercent(50,true)===50&&armorIgnorePercent(100,true)===100,'no double halving or restoring bypassed armor');
  let invalid=false;try{manualNumber('2.5','Dice',1,100)}catch{invalid=true}check(invalid,'invalid dice');
  const data={kind:'group',creator:'gm',title:'Perception',skill:'Perception',rollMode:'roll',dv:13,hideDV:true,rows:[{user:'p1',actor:'Actor.1',name:'Pex',state:'waiting'},{user:'p2',actor:'Actor.2',name:'NPC <unsafe>',state:'waiting'}]};
  const message={id:'group',visible:true,whisper:[],flags:{'pneuma-combattools':{manualRoll:data}},async update(changes){this.flags['pneuma-combattools'].manualRoll=changes['flags.pneuma-combattools.manualRoll'];this.content=changes.content;}};
  game.messages.set('group',message);
  const send=(user,request)=>handleManualRequest({message:'group',user,request});
  let rejected=false;try{await send('p2',{action:'claim',row:'p1',nonce:'bad'})}catch{rejected=true}check(rejected,'ownership');
  await send('p1',{action:'claim',row:'p1',nonce:'a'});
  rejected=false;try{await send('p1',{action:'claim',row:'p1',nonce:'b'})}catch{rejected=true}check(rejected,'duplicate claim');
  await send('gm',{action:'claim',row:'p2',nonce:'c'});
  await send('p1',{action:'commit',row:'p1',nonce:'a',total:14,html:'<b>14</b>'});
  await send('p1',{action:'commit',row:'p1',nonce:'a',total:999,html:'wrong'});
  await send('gm',{action:'reset',row:'p2'});
  const saved=message.flags['pneuma-combattools'].manualRoll;
  check(saved.rows[0].total===14&&saved.rows[1].state==='waiting','preserve rows and idempotent commit');
  check(message.content.includes('rollcard-top')&&message.content.includes('rollcard-bottom')&&message.content.includes('cpr-block pneuma-group-heading'),'native card sections');
  check(!message.content.includes('DV 13')&&message.content.includes('&lt;unsafe&gt;'),'hidden DV and escape');
  game.user=game.users.get('p1');cards.innerHTML=message.content;cards.querySelector('.pneuma-group-details').removeAttribute('hidden');cards.querySelector('.pneuma-group-details').style.display='block';bindManualCard(message,cards);check(!cards.textContent.includes('DV 13')&&cards.querySelectorAll('button').length===0,'player controls');
  const total=cards.querySelector('.pneuma-group-total'),details=cards.querySelector('.pneuma-group-details');
  check(!cards.querySelector('summary')&&details.hidden&&getComputedStyle(details).display==='none','details label removed and initially hidden');
  details.innerHTML='<div class="d10-data-details hide" style="display:none">INT + 8; Accounting + 1; Mods: -2</div>';
  total.click();check(!details.hidden&&total.getAttribute('aria-expanded')==='true'&&!details.firstElementChild.classList.contains('hide')&&getComputedStyle(details.firstElementChild).display==='block'&&getComputedStyle(details).display==='block','total opens expanded modifiers');
  total.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter'}));check(details.hidden&&getComputedStyle(details).display==='none','keyboard closes details');
  total.dispatchEvent(new KeyboardEvent('keydown',{key:' '}));check(!details.hidden,'space opens details');
  check(getComputedStyle(cards.querySelector('[data-outcome="success"]')).color==='rgb(40, 122, 53)','green success');
  const fail=document.createElement('span');fail.className='pneuma-group-outcome';fail.dataset.outcome='fail';cards.append(fail);check(getComputedStyle(fail).color==='rgb(181, 32, 32)','red fail');
  game.user=game.users.get('gm');cards.innerHTML=message.content;bindManualCard(message,cards);check(cards.textContent.includes('DV 13')&&cards.querySelectorAll('button').length===1,'GM controls');
  registerManualRolls();hooks.renderChatLog[0](null,[document.body]);document.querySelector('.fa-dice-d20').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter'}));check(!!document.querySelector('[data-roll-choice=group]'),'GM menu');document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape'}));check(!document.querySelector('.pneuma-roll-flyout'),'escape closes');
  game.user=game.users.get('p1');openManualRolls();check(!document.querySelector('[data-roll-choice=group]'),'player menu');document.body.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));check(!document.querySelector('.pneuma-roll-flyout'),'outside click closes');game.user=game.users.get('gm');
  await basePrompt();window.baseDialog=dialog;let holder=document.createElement('div');holder.innerHTML=baseDialog.content;baseDialog.render([holder]);check(holder.querySelector(".pneuma-custom-roll").disabled,"custom starts locked");check(Object.keys(baseDialog.buttons).join()==='roll',"single roll button");window.customFormPreview=baseDialog.content;holder.querySelector('[name=base]').value='7';facesQueue.push([10],[4]);await baseDialog.buttons.roll.callback([holder]);check(lastRoll.resultTotal===21&&lastRoll.criticalRoll===4,'native Critical Success on natural 10');
  facesQueue.push([1],[8]);await baseDialog.buttons.roll.callback([holder]);check(lastRoll.resultTotal===0&&lastRoll.criticalRoll===8,'native Critical Failure on natural 1');
  holder.querySelector('[value=custom]').checked=true;holder.querySelector('[value=custom]').dispatchEvent(new Event('change',{bubbles:true}));check(!holder.querySelector('.pneuma-custom-roll').disabled,'custom unlocks dice');
  holder.querySelector('[name=title]').value='Custom <test>';
  holder.querySelector('[name=customDice]').value='20';holder.querySelector('[name=customSides]').value='100';
  facesQueue.push(Array(20).fill(100));await baseDialog.buttons.roll.callback([holder]);check(created.content.includes('20d100+7 = 2007')&&created.content.includes('Custom &lt;test&gt;'),'custom shares label and modifier');
  for(const [count,sides] of [[21,6],[1,101],[0,6],[1,0],[1.5,6]]){
    holder.querySelector('[name=customDice]').value=String(count);holder.querySelector('[name=customSides]').value=String(sides);
    let rejected=false;try{await baseDialog.buttons.roll.callback([holder])}catch{rejected=true}check(rejected,'custom dice range validation');
  }
  holder.querySelector('[name=customDice]').value='1';holder.querySelector('[name=customSides]').value='1';holder.querySelector('[name=base]').value='-2';facesQueue.push([1]);await baseDialog.buttons.roll.callback([holder]);check(created.content.includes('1d1-2 = -1'),'minimum custom dice and negative modifier');holder.querySelector('[value=standard]').checked=true;holder.querySelector('[value=standard]').dispatchEvent(new Event('change',{bubbles:true}));check(holder.querySelector('.pneuma-custom-roll').disabled,'switching back locks custom');
  game.user=game.users.get('p1');game.user.character=actor;window.canvas={tokens:{controlled:[]}};
  actor.system={stats:{ref:{value:6},luck:{value:2,max:8}}};actor.getStat=stat=>actor.system.stats[stat].value;
  openManualRolls();check(!!document.querySelector('[data-roll-choice=stat]')&&!document.querySelector('[data-roll-choice=group]'),'player STAT menu');document.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown'}));check(document.activeElement.dataset.rollChoice==='critical','keyboard navigation');document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape'}));
  await statPrompt();holder.innerHTML=promptData.content;check(holder.textContent.includes('LUCK (2)'),'current stat instead of maximum');
  holder.querySelector('[name=stat]').value='ref';actor.system.stats.ref.value=5;
  for(const [die,outcome] of [[4,'success'],[5,'fail'],[10,'fail'],[1,'success']]) {
    facesQueue.push([die]);await promptData.callback([holder]);
    check(created.content.includes('data-stat-outcome="'+outcome+'"')&&created.content.includes('REF 5'),'strict current-stat comparison');
    check(lastRoll.resultTotal===die&&lastRoll._critRoll===null&&facesQueue.length===0,'single d10 without Critical Success/Critical Failure');
  }
  canvas.tokens.controlled=[{actor:{isOwner:false}}];let denied=false;try{await statPrompt()}catch{denied=true}check(denied,'unowned selection rejected');
  canvas.tokens.controlled=[{actor},{actor}];denied=false;try{await statPrompt()}catch{denied=true}check(denied,'multiple selection rejected');
  canvas.tokens.controlled=[{actor}];await statPrompt();check(promptData.title==='STAT roll','owned token supported');
  game.user=game.users.get('gm');
  await damagePrompt();holder.innerHTML=promptData.content;check(holder.querySelector('[name=armor]').checked,'armor default');check(holder.querySelector('[name=dice]').tagName==='SELECT'&&[...holder.querySelector('[name=dice]').options].map(o=>o.text).join(',')==='1d6,2d6,3d6,4d6,5d6,6d6,7d6,8d6','damage dice dropdown');window.damageFormPreview=promptData.content;
  facesQueue.push([6,6,2]);await promptData.callback([holder]);check(lastRoll.resultTotal===14&&created.flags['pneuma-combattools'].manualRoll.damage.result.sixes===2,'native damage and critical');
  holder.querySelector('[name=armor]').checked=false;facesQueue.push([3,2,1]);await promptData.callback([holder]);check(created.flags['pneuma-combattools'].manualRoll.damage.result.values.interactArmor===false&&lastRoll.rollCardExtraArgs.ignoreArmorPercent===0,'no armor or ablation');
  const damage=created.flags['pneuma-combattools'].manualRoll;damage.damage.result.values.ignorePercent=0;damage.damage.result.values.interactArmor=true;
  const dm={...message,id:'damage',flags:{'pneuma-combattools':{manualRoll:damage}}};game.messages.set('damage',dm);
  cards.innerHTML=manualContent(damage);bindManualCard(dm,cards);bindHalfArmor(cards);check(cards.querySelectorAll('.pneuma-damage-status-slot').length===3,'three effect slots');
  cards.querySelector('.pneuma-half-armor').click();check(cards.querySelectorAll('.pneuma-damage-status-slot').length===3,'shared three effect slots');check(cards.querySelector('.pneuma-damage-recipient').textContent.trim()==='to selected target','shared recipient label');cards.querySelector('.pneuma-apply-damage').click();await new Promise(resolve=>setTimeout(resolve,20));check(applied.halfArmor===true,'half armor passed to apply');
  await handleManualRequest({message:'damage',user:'gm',request:{action:'effects',effects:['prone']}});check(dm.flags['pneuma-combattools'].manualRoll.damage.statusEffects[0]==='prone','effects saved');
  cards.insertAdjacentHTML('beforeend','<div class="rollcard" id="native"><a data-action="applyDamage" data-ignore-armor-percent="0">Native apply damage</a></div>');bindHalfArmor(cards);bindHalfArmor(cards);
  const native=document.querySelector('#native');check(native.querySelectorAll('button').length===2,'no duplicate button');native.querySelector('.pneuma-half-armor').click();check(native.querySelector('a').dataset.ignoreArmorPercent==='50','native toggle');native.querySelector('.pneuma-half-armor').click();check(native.querySelector('a').dataset.ignoreArmorPercent==='0','native restore');
  const interact=native.querySelector('.pneuma-interact-armor');check(interact.getAttribute('aria-pressed')==='true','armor default checked');
  interact.click();check(native.querySelector('a').dataset.ignoreArmorPercent==='100'&&native.querySelector('a').dataset.ablation==='0'&&native.querySelector('.pneuma-half-armor').disabled,'native armor bypass and no ablation');
  interact.click();check(native.querySelector('a').dataset.ignoreArmorPercent==='0'&&!native.querySelector('.pneuma-half-armor').disabled,'restore armor interaction');
  game.settings.register=(_m,_k,options)=>{window.armorSetting=options};registerHalfArmor();check(armorSetting.scope==='world'&&armorSetting.default===false&&armorSetting.name==='Show armor controls on normal damage cards','GM world setting');
  const armorHook=hooks.renderChatMessage.at(-1);game.settings.get=()=>false;
  cards.innerHTML=manualContent(damage);armorHook(dm,[cards]);check(cards.querySelector('.pneuma-interact-armor'),'manual keeps controls');
  const normal={flags:{'pneuma-combattools':{exchange:{damage:damage.damage}}}};
  armorHook(normal,[cards]);check(!cards.querySelector('.pneuma-half-armor')&&!cards.querySelector('.pneuma-interact-armor'),'normal hides both controls');
  game.settings.get=()=>true;armorHook(normal,[cards]);check(cards.querySelector('.pneuma-interact-armor'),'normal setting restores controls');
  const injury={uuid:'Compendium.injury',name:'Broken Ribs',type:'criticalInjury',img:'',system:{penalty:5},effects:[{toObject:()=>({name:'Effect'})}]};
  const table={name:'Critical Injuries (Body)',async roll(){return {results:[{text:injury.name}],roll:await new Roll('2d6').evaluate()}}};
  game.packs=new Map([['tables',{getIndex:async()=>{},index:[{name:table.name}]}],['injuries',{getIndex:async()=>{}}]]);
  game.settings.get=(_m,key)=>key==='criticalInjuryRollTableCompendium'?'tables':false;
  window.nativeUtils={GetCompendiumIdByLabel:()=> 'injuries',GetCompendiumDoc:async pack=>pack==='tables'?table:injury};
  facesQueue.push([2,3]);await criticalPrompt();holder.innerHTML=promptData.content;await promptData.callback([holder]);
  check(created.flags['pneuma-combattools'].manualRoll.injury.name==='Broken Ribs','native injury table');
  const im={...message,id:'injury',flags:{'pneuma-combattools':{manualRoll:created.flags['pneuma-combattools'].manualRoll}}};game.messages.set('injury',im);
  const oldFrom=fromUuid;window.fromUuid=async id=>id===injury.uuid?injury:oldFrom(id);
  actor.createEmbeddedDocuments=async(type,items)=>{window.injuryCreated={type,items};};
  await handleManualRequest({message:'injury',user:'gm',request:{action:'injury',target:'Token.1'}});
  check(injuryCreated.type==='Item'&&injuryCreated.items[0].effects[0].name==='Effect'&&!im.flags['pneuma-combattools'].manualRoll.injuryBusy,'native injury item and effects applied');
  cards.insertAdjacentHTML('afterbegin',message.content);bindManualCard(message,cards);
  window.damagePreviewCard=dm;
  return 'Passed: native Critical Success/Critical Failure dice, damage, armor defaults/bypass/half, effect slots, group claims/permissions/results, hidden DV, menu keyboard and native card controls.';
 });
 console.log(result);
 await page.evaluate(()=>{
   const preview=document.createElement('div');preview.id='damage-preview';preview.innerHTML=manualContent(damagePreviewCard.flags['pneuma-combattools'].manualRoll);document.body.prepend(preview);bindManualCard(damagePreviewCard,preview);
 });
 const applyRow=page.locator('#damage-preview .pneuma-damage-recipient'),slots=page.locator('#damage-preview .pneuma-damage-status-effects');
 const rowBox=await applyRow.boundingBox(),slotBox=await slots.boundingBox();
 assert.ok(slotBox.x>=rowBox.x+rowBox.width,'Effects sit to the right of the recipient');
 assert.ok(Math.abs((slotBox.y+slotBox.height/2)-(rowBox.y+rowBox.height/2))<4,'Effects align with the apply row');
 await page.locator('#damage-preview').screenshot({path:process.env.TEMP+'/pct-shared-damage.png'});
 await page.evaluate(()=>document.getElementById('damage-preview').remove());

 await page.evaluate(()=>{document.querySelector('.pneuma-group-total')?.click();});
 await page.screenshot({path:process.env.TEMP+'/pct-manual-rolls.png',fullPage:true});
 await page.evaluate(()=>{
  document.querySelector('#cards').innerHTML='<div class="pneuma-roll-dialog" style="margin-top:20px;padding:16px;border:1px solid #888;width:350px"><h3>Manual damage roll</h3>'+damageFormPreview+'<button style="width:100%">Roll</button></div>';
  const icon=document.querySelector('[data-pneuma-manual-rolls]');icon.style.position='fixed';icon.style.bottom='20px';icon.style.right='30px';icon.textContent='Dice';openManualRolls(icon);
 });
 await page.screenshot({path:process.env.TEMP+'/pct-roll-menu-layout.png',fullPage:true});
 await page.evaluate(()=>{document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape'}));document.querySelector('#cards').innerHTML='<div class="pneuma-roll-dialog" style="padding:16px;border:1px solid #888;width:350px"><h3>Cyberpunk roll</h3>'+customFormPreview+'<button style="width:100%">Roll</button></div>';});
 await page.screenshot({path:process.env.TEMP+'/pct-custom-roll.png',fullPage:true});
} finally {await browser.close()}
