import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {chromium}=await import(process.env.PNEUMA_PLAYWRIGHT_MODULE);
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const page=await browser.newPage();page.on('pageerror',error=>console.error(error.message));await page.setContent('<style>#token-hud{position:absolute;left:120px;top:100px;width:120px;height:120px}#token-hud .col{position:absolute;width:40px;height:100%;display:flex;flex-direction:column}#token-hud .col.right{right:-50px}#token-hud .control-icon{width:40px;height:40px}</style><div id="token-hud" class="placeable-hud"><div class="col right"></div><button data-native>Native</button></div>');
 await page.addScriptTag({content:await readFile(process.env.PNEUMA_JQUERY_SOURCE,'utf8')});await page.addScriptTag({content:await readFile(process.env.PNEUMA_HANDLEBARS_SOURCE,'utf8')});
 await page.evaluate(template=>{
  Handlebars.registerHelper('eq',(a,b)=>a===b);Handlebars.registerHelper('localize',s=>s);window.renderTemplate=async()=>Handlebars.compile(template)(window.renderData);
  window.hooks={};window.Hooks={on:(n,f)=>(hooks[n]??=[]).push(f),once:(n,f)=>(hooks[n]??=[]).push(f)};
  window.foundry={utils:{getProperty:(o,p)=>p.split('.').reduce((v,k)=>v?.[k],o)},data:{fields:{ColorField:class{}}}};
  window.settings={};window.game={system:{id:'cyberpunk-red-core'},user:{isGM:false},settings:{register:(_m,k,c)=>settings[k]=c.default,get:(_m,k)=>settings[k],set:async(_m,k,v)=>{settings[k]=v;}},i18n:{localize:s=>s,format:s=>s}};
  class NativeToken{_canHUD(){return true;}_onClickRight(){canvas.tokens.controlled=[this];}_onUnclickRight(){}_onClickRight2(){}}
  class NativeHUD{get template(){return 'native';}getData(){return{id:'token-hud',classes:'placeable-hud'};}activateListeners(){}render(){window.renders=(window.renders??0)+1;}}
  window.CONFIG={Token:{objectClass:NativeToken,hudClass:NativeHUD}};window.BasePlaceableHUD=class{};window.Ruler={STATES:{MEASURING:1}};
  const layer={controlled:[]};window.canvas={tokens:layer,activeLayer:layer,stage:{},controls:{ruler:{state:0}}};window.ui={notifications:{error:text=>window.failure=text}};
 },await readFile('src/templates/combat-hud.hbs','utf8'));
 const main=(await readFile('dist/scripts/main.js','utf8')).replace(/^import .*;\s*/gm,'');
 const names=[...new Set([...main.matchAll(/^\s+(register\w+)\(\);/gm)].map(m=>m[1]))].filter(n=>n!=='registerSelfCTH');
 const stubs=names.map(name=>`const ${name}=()=>{};`).join('\n')+'\nconst DEFAULT_ICON_COLOR="#ffc36a",installIconColorNormalization=()=>{},tokenEncounter=()=>game.combat,displayedEncounter=()=>game.combat;const openTurnMarkerSettings=token=>{window.animationOpened=true;window.indicatorToken=token;},registerQuickhack=()=>{},bindWeaponAmmo=()=>{},decorateItemList=()=>{},connectionFor=()=>undefined,quickhackEnabled=()=>false,forceOutEntries=()=>[],attackEntries=()=>[],thrownEntries=()=>[],grenadeEntries=()=>window.grenades??[],grappleMenu=()=>window.grappleActions??[],useGrapple=async(s,t,a)=>{window.grappleUsed=a;},trackingCombat=()=>undefined;';
 const emp=(await readFile('dist/scripts/effect-duration.js','utf8'))+'\n'+(await readFile('dist/scripts/emp-rules.js','utf8')).replace(/^import .*;\s*/gm,''),self=(await readFile('dist/scripts/self-cth.js','utf8')).replace(/^import .*;\s*/gm,'');
 await page.addScriptTag({type:'module',content:emp+'\n'+self+'\n'+stubs+'\n'+main+'\nhooks.init.forEach(fn=>fn());window.loaded=true;'});await page.waitForFunction(()=>window.loaded);
 await page.evaluate(()=>{
  window.own=Object.assign(new CONFIG.Token.objectClass(),{isOwner:true,isVisible:true,actor:{isOwner:true,items:[{type:'cyberware',name:'Kerenzikov',system:{isInstalledInActor:true}}]},document:{uuid:'Token.own'}});
  window.enemy=Object.assign(new CONFIG.Token.objectClass(),{isOwner:false,isVisible:true,actor:{isOwner:false,items:[]},document:{uuid:'Token.enemy'}});
  window.event={shiftKey:false,getLocalPosition:()=>({x:0,y:0}),stopPropagation(){}};
  window.rolls=[];game.combat={uuid:'Combat.c',started:true,combatants:[{id:'c',initiative:15,token:own.document}],rollInitiative:async(...args)=>rolls.push(args)};
  game.combats=new Map();canvas.tokens.controlled=[own];window.hud=new CONFIG.Token.hudClass();canvas.tokens.hud=hud;
  window.show=async(token,shift=false)=>{event.shiftKey=shift;token._onClickRight(event);hud.object=token;hud.element=$('#token-hud');hud.element.find('.pneuma-combat-column').remove();window.renderData=hud.getData();if(renderData.standalone)hud.element.html(Handlebars.compile(window.sourceTemplate)(renderData));for(const fn of hooks.renderTokenHUD)await fn(hud,hud.element,renderData);};
 });
 await page.evaluate(template=>window.sourceTemplate=template,await readFile('src/templates/combat-hud.hbs','utf8'));
 await page.evaluate(()=>show(own));assert.equal(await page.locator('[data-self-cth]').count(),1);assert.equal(await page.locator('[data-combat-action]').count(),0);assert.equal(await page.locator('[data-self-initiative]').count(),0);assert.equal(await page.locator('[data-native]').count(),1);
 await page.addStyleTag({content:await readFile('dist/styles/pneuma-combattools.css','utf8')});
 await page.locator('[data-self-settings-toggle]').dispatchEvent('click');
 assert.equal(await page.locator('[data-self-settings-toggle]').getAttribute('aria-expanded'),'true');
 assert.equal(await page.locator('[data-self-settings-menu] button').first().innerText(),'Animated Turn Indicator');
 await page.screenshot({path:process.env.TEMP+'/pct-self-cth-settings.png'});
 await page.locator('[data-turn-animation]').click();assert.equal(await page.evaluate(()=>animationOpened),true);
 assert.equal(await page.locator('[data-self-settings-menu]').isVisible(),false);
 await page.evaluate(()=>document.querySelector('#token-hud').style.setProperty('--pneuma-cth-icon-color','#12ab34'));
 assert.equal(await page.locator('[data-self-cth] > [data-self-alert-hud] .fa-bell').count(),1);
 assert.equal(await page.locator('[data-self-cth] > section:not([hidden]), [data-self-cth] > strong, [data-self-cth] .notes').count(),0);
 assert.equal(await page.locator('[data-roll-initiative]').count(),0);
 assert.equal(await page.locator('[data-self-thrown-toggle]').count(),1);
 await page.locator('[data-self-thrown-toggle]').dispatchEvent('keydown',{key:'Enter'});assert.equal(await page.locator('[data-self-thrown-menu]').evaluate(e=>e.hidden),false);assert.equal(await page.locator('[data-self-thrown-menu]').isVisible(),true);assert.equal(await page.locator('[data-self-thrown-menu]').evaluate(e=>e.classList.contains('status-effects')),false);
 await page.locator('[data-self-thrown-toggle]').dispatchEvent('click');assert.equal(await page.locator('[data-self-thrown-menu]').evaluate(e=>e.hidden),true);
 assert.equal(await page.locator('[data-self-alert-hud] > i').evaluate(n=>getComputedStyle(n).color),'rgb(18, 171, 52)');
 await page.evaluate(()=>settings.eyeHUD=false);
 await page.locator('[data-self-alert-hud]').dispatchEvent('click');await page.waitForFunction(()=>settings.eyeHUD===true);
 await page.evaluate(()=>show(own));
 await page.locator('[data-self-alert-hud]').dispatchEvent('keydown',{key:'Enter'});await page.waitForFunction(()=>settings.eyeHUD===false);
 await page.evaluate(()=>{settings.pneumaHomebrew=true;return show(own,true);});assert.equal(await page.locator('[data-self-cth] > [data-self-initiative] .fa-dice-d10').count(),1);assert.equal(await page.locator('[data-self-initiative] > i').evaluate(n=>getComputedStyle(n).color),'rgb(18, 171, 52)');assert.equal(await page.locator('[data-combat-action]').count(),0);
 await page.locator('[data-self-initiative]').dispatchEvent('click');assert.deepEqual(await page.evaluate(()=>rolls),[[['c'],{updateTurn:true}]]);
 await page.evaluate(()=>{settings.pneumaHomebrew=false;});await page.locator('[data-self-initiative]').dispatchEvent('click');assert.equal(await page.evaluate(()=>rolls.length),1);
 await page.evaluate(()=>{canvas.tokens.controlled=[own];return show(enemy);});assert.equal(await page.locator('[data-combat-action]').count(),3);assert.equal(await page.locator('[data-self-initiative]').count(),0);
 await page.evaluate(()=>{document.querySelector("#token-hud").innerHTML='<div class="col right"></div>';window.grappleActions=[{action:"escape",label:"Escape — Attacker"}];return show(own);});
 assert.equal(await page.locator('[data-self-close-toggle]').count(),1);
 await page.locator('[data-self-close-toggle]').dispatchEvent('click');
 assert.equal(await page.locator('[data-self-close-menu]').isVisible(),true);
 assert.equal(await page.locator('[data-self-grapple]').innerText(),'Escape — Attacker');
 await page.locator('[data-self-grapple]').click();assert.equal(await page.evaluate(()=>grappleUsed),'escape');
 await page.evaluate(()=>{window.grappleActions=[{action:"choke",label:"Choke — Defender",disabled:true}];return show(own);});
 assert.equal(await page.locator('[data-self-grapple]').isDisabled(),true);
 // Reproduce a narrow native icon column: a self menu must not stretch it or its controls.
 await page.addStyleTag({content:'#token-hud{position:absolute;left:120px;top:100px;width:120px;height:120px;background:#303b43}#token-hud .col{position:absolute;width:40px;height:100%;display:flex;flex-direction:column}#token-hud .col.right{right:-50px}#token-hud .control-icon{box-sizing:border-box;flex:0 0 40px;width:40px;height:40px;margin:4px 0;background:#222;color:white}#token-hud button{color:black;border:2px solid #888;line-height:32px}body{background:#17222c}'});
 await page.evaluate(()=>{window.grappleActions=[{action:'choke',label:'Choke — Crick',title:'Already choked this round',disabled:true},{action:'throw',label:'Throw — Crick'},{action:'release',label:'Release — Crick'}];return show(own);});
 const toggle=page.locator('[data-self-close-toggle]'),thrown=page.locator('[data-self-thrown-toggle]');
 const before=await thrown.boundingBox();
 await toggle.click();
 assert.deepEqual(await thrown.boundingBox(),before,'Opening grapple actions never moves the icon column');
 const menu=page.locator('[data-self-close-menu]'),button=page.locator('[data-self-grapple="throw"]');
 assert.equal(await menu.evaluate(n=>getComputedStyle(n).position),'absolute');
 assert.equal((await menu.boundingBox()).width,240);
 assert.equal(await button.evaluate(n=>getComputedStyle(n).color),'rgb(238, 238, 238)');
 assert.equal(await menu.locator(".combat-heading").innerText(),"Close Combat");
 const background=await button.evaluate(n=>getComputedStyle(n).backgroundColor);
 const rect=await button.boundingBox();assert.equal(rect.height,28);await button.hover();assert.deepEqual(await button.boundingBox(),rect);
 assert.notEqual(await button.evaluate(n=>getComputedStyle(n).backgroundColor),background,'Hover visibly highlights the action');
 assert.equal(await button.locator('i').count(),1);
 assert.equal(await button.locator('span').evaluate(n=>n.scrollWidth<=n.clientWidth),true,'Action and target fit one line');
 assert.equal(await page.locator('[data-self-grapple="choke"]').isDisabled(),true);
 await page.screenshot({path:process.env.TEMP+'/pct-self-cth-fixed.png'});
 await button.click();assert.equal(await page.evaluate(()=>grappleUsed),'throw');
 await page.evaluate(()=>{window.grenades=[{id:'grenade',name:'Frag Grenade',img:'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10" fill="gray"/></svg>'}];return show(own);});
 await page.locator('[data-self-thrown-toggle]').click();
 assert.equal(await page.locator('[data-self-thrown-menu] .combat-heading').innerText(),'Thrown Weapons & Grenades');
 const grenade=page.locator('[data-self-throw="grenade"]');
 assert.equal(await grenade.locator('img').count(),1);
 assert.equal(await page.locator('[data-self-throw="__improvised"] img').count(),1);
 const normal=await grenade.evaluate(n=>getComputedStyle(n).backgroundColor),bounds=await grenade.boundingBox();
 await grenade.hover();assert.notEqual(await grenade.evaluate(n=>getComputedStyle(n).backgroundColor),normal);assert.deepEqual(await grenade.boundingBox(),bounds);
 await page.screenshot({path:process.env.TEMP+'/pct-self-cth-grenades.png'});
 await page.evaluate(()=>{game.user.isGM=true;canvas.tokens.controlled=[own];return show(enemy);});
 assert.equal(await page.locator('[data-token-indicator]').count(),1);await page.locator('[data-token-indicator]').click();assert.equal(await page.evaluate(()=>indicatorToken===enemy.document),true);
 await page.evaluate(()=>{canvas.tokens.controlled=[own];document.querySelector('#token-hud').innerHTML='<div class="col right"></div>';return show(own);});await page.locator('[data-self-settings-toggle]').click();await page.locator('[data-turn-animation]').click();assert.equal(await page.evaluate(()=>indicatorToken===own.document),true);
 console.log('Self CTH browser checks passed: own-token replacement, native controls retained, setting toggle, Shift-right-click, D10 native reroll and target actions.');
}finally{await browser.close();}
