import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
const {chromium}=await import(process.env.PNEUMA_PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({channel:'msedge',headless:true});
try {
 const page=await browser.newPage({viewport:{width:600,height:500}});
 await page.setContent('<style>body{background:#333;padding:30px;font:13px Arial}button{font:inherit}button:disabled{opacity:.4}</style><div id="token-hud"></div>');
 await page.addStyleTag({content:await readFile('dist/styles/pneuma-combattools.css','utf8')});
 if(process.env.PNEUMA_FONT_AWESOME_CSS)await page.addStyleTag({url:process.env.PNEUMA_FONT_AWESOME_CSS});
 await page.addScriptTag({path:process.env.PNEUMA_HANDLEBARS_SCRIPT||tmpdir()+'/pneuma-handlebars-4.7.8.min.js'});
 await page.addScriptTag({content:(await readFile('dist/scripts/weapon-ammo.js','utf8')).replaceAll('export ','')+'\nwindow.bindWeaponAmmo=bindWeaponAmmo;window.refreshWeaponAmmo=refreshWeaponAmmo;'});
 await page.evaluate(template=>{
  Handlebars.registerHelper('eq',(a,b)=>a===b);Handlebars.registerHelper('localize',s=>s.split('.').at(-1));
  window.foundry={utils:{getProperty:(o,p)=>p.split('.').reduce((v,k)=>v[k],o)}};window.ui={notifications:{warn:()=>{},error:e=>{throw Error(e);}}};
  window.calls=[];
  const gun=(id,value)=>({id,uuid:'Actor.test.Item.'+id,system:{isRanged:true,weaponType:'smg',magazine:{value,max:30}},reserve:{system:{amount:60}},getMagazineSpace(){return 30-this.system.magazine.value;},getInstalledItems(){return [this.reserve];},async reload(){calls.push('reload');this.system.magazine.value=30;},async load(){calls.push('change');}});
  window.actor={isOwner:true,items:new Map([['empty',gun('empty',0)],['partial',gun('partial',9)],['full',gun('full',30)]])};
  const weapons=[...actor.items.keys()].map(id=>({id,name:{empty:'Empty SMG',partial:'Partial SMG',full:'Full SMG'}[id],category:'attack',gunAmmo:true,autofire:true}));
  weapons.push({id:'bow',name:'Bow',category:'attack'});
  const root=document.querySelector('#token-hud');root.innerHTML=Handlebars.compile(template)({weapons});
  root.querySelector('.combat-weapons').hidden=false;root.querySelector('.pneuma-combat-menu').classList.add('active');
  root.querySelector('.combat-heading').textContent='Ranged weapons';root.querySelector('.combat-empty').hidden=true;
  bindWeaponAmmo(root,actor);
 },await readFile('dist/templates/combat-hud.hbs','utf8'));
 const row=id=>page.locator(`[data-weapon-ammo="${id}"]`);
 assert.equal(await row('empty').locator('.combat-ammo-menu').isVisible(),true);
 assert.equal(await row('partial').locator('.combat-ammo-menu').isVisible(),false);
 assert.equal(await row('empty').locator('[data-attack-mode="aimed"]').isVisible(),false);
 const initialHeight=(await row('partial').boundingBox()).height;
 assert.equal(await row('partial').locator('[data-attack-mode="autofire"]').isDisabled(),true);
 assert.equal(await row('partial').locator('.combat-weapon-name').getAttribute('aria-disabled'),'false');
 assert.equal(await row('empty').locator('.combat-weapon-name').getAttribute('aria-disabled'),'true');
 assert.equal(await page.locator('[data-item-id="bow"]').first().getAttribute('aria-disabled'),null);
 await row('full').locator('.combat-weapon-name').click({button:'right'});
 assert.equal(await row('full').locator('[data-attack-mode="autofire"]').isVisible(),false);
 assert.equal((await row('full').boundingBox()).height,initialHeight);
 await row('full').locator('.combat-weapon-name').click({button:'right'});
 assert.equal(await row('full').locator('[data-attack-mode="autofire"]').isVisible(),true);
 assert.equal(await row('full').locator('.combat-ammo-menu').isVisible(),false);
 await row('full').locator('.combat-weapon-name').click({button:'right'});
 assert.equal(await row('full').locator('[data-ammo-action="reload"]').isDisabled(),true);
 assert.equal(await row('full').locator('[data-ammo-action="reload"]').getAttribute('title'),'Magazine full');
 await row('full').locator('[data-ammo-action="change"]').click();
 assert.deepEqual(await page.evaluate(()=>calls),['change']);
 await row('partial').locator('.combat-weapon-name').focus();await page.keyboard.press('Shift+F10');
 assert.equal(await row('partial').locator('.combat-ammo-menu').isVisible(),true);
 assert.equal((await row('partial').boundingBox()).height,initialHeight);
 const nameBox=await row('partial').locator('.combat-weapon-name').boundingBox();
 const reloadBox=await row('partial').locator('[data-ammo-action="reload"]').boundingBox();
 assert.equal(reloadBox.y,nameBox.y);assert.equal(reloadBox.width,24);
 assert.equal(await row('partial').locator('[data-ammo-action="reload"]').getAttribute('aria-label'),'Reload');
 assert.equal(await row('partial').locator('[data-ammo-action="change"]').getAttribute('aria-label'),'Change Ammo');
 await page.evaluate(()=>{actor.items.get('partial').reserve.system.amount=0;refreshWeaponAmmo(document.querySelector('#token-hud'),actor);});
 assert.equal(await row('partial').locator('[data-ammo-action="reload"]').getAttribute('title'),'No reserve ammunition');
 await page.evaluate(()=>document.fonts.ready);
 await page.screenshot({path:tmpdir()+'/pneuma-weapon-ammo.png'});
 await row('empty').locator('[data-ammo-action="reload"]').click();
 assert.deepEqual(await page.evaluate(()=>calls),['change','reload']);
 assert.equal(await row('empty').locator('[data-attack-mode="autofire"]').isDisabled(),false);
 assert.equal(await row('empty').locator('.combat-ammo-menu').isVisible(),false);
 assert.equal(await row('empty').locator('[data-attack-mode="autofire"]').isVisible(),true);
 await page.evaluate(()=>{actor.items.get('empty').system.magazine.value=0;refreshWeaponAmmo(document.querySelector('#token-hud'),actor);});
 assert.equal(await row('empty').locator('.combat-ammo-menu').isVisible(),true);
 // aria-disabled blocks attacking, but a real context click remains available.
 await row('empty').locator('.combat-weapon-name').click({button:'right',force:true});
 assert.equal(await row('empty').locator('.combat-ammo-menu').isVisible(),true);
 assert.equal(await row('empty').locator('[data-attack-mode="autofire"]').isVisible(),false);
 console.log('Weapon ammo rendered controls passed; screenshot: '+tmpdir()+'/pneuma-weapon-ammo.png');
} finally {await browser.close();}
